// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/client.service.proto

package com.ljzn.grpc.client;

public final class ClientService {
  private ClientService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrisonSystem_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrisonSystem_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrisonSystem_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrisonSystem_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrisonSystem_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrisonSystem_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrisonSystem_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrisonSystem_HeartbeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033client/client.service.proto\022\014PrisonSys" +
      "tem\032\033client/client.message.proto\"R\n\014Logi" +
      "nRequest\022+\n\006client\030\001 \001(\0132\033.PrisonSystem." +
      "ClientMessage\022\025\n\rclient_secret\030\002 \001(\t\"@\n\r" +
      "LoginResponse\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002" +
      " \001(\t\022\020\n\010belongId\030\003 \001(\t\"\'\n\020HeartbeatReque" +
      "st\022\023\n\013deviceSeril\030\001 \001(\t\"E\n\021HeartbeatResp" +
      "onse\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\021\n\tt" +
      "imeStamp\030\003 \001(\0032\247\001\n\021ClientAuthService\022B\n\005" +
      "Login\022\032.PrisonSystem.LoginRequest\032\033.Pris" +
      "onSystem.LoginResponse\"\000\022N\n\tHeartBeat\022\036." +
      "PrisonSystem.HeartbeatRequest\032\037.PrisonSy" +
      "stem.HeartbeatResponse\"\000B!\n\024com.ljzn.grp" +
      "c.clientP\001\242\002\006CLIENTb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ljzn.grpc.client.ClientMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_PrisonSystem_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PrisonSystem_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrisonSystem_LoginRequest_descriptor,
        new java.lang.String[] { "Client", "ClientSecret", });
    internal_static_PrisonSystem_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PrisonSystem_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrisonSystem_LoginResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "BelongId", });
    internal_static_PrisonSystem_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PrisonSystem_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrisonSystem_HeartbeatRequest_descriptor,
        new java.lang.String[] { "DeviceSeril", });
    internal_static_PrisonSystem_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PrisonSystem_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrisonSystem_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "TimeStamp", });
    com.ljzn.grpc.client.ClientMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
