// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/client.message.proto

package com.ljzn.grpc.client;

/**
 * Protobuf type {@code PrisonSystem.ClientMessage}
 */
public  final class ClientMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PrisonSystem.ClientMessage)
    ClientMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientMessage.newBuilder() to construct.
  private ClientMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientMessage() {
    deviceSeril_ = "";
    deviceName_ = "";
    deviceType_ = 0;
    deviceAddress_ = "";
    deviceAccuracy_ = "";
    serviceAccount_ = "";
    servicePassword_ = "";
    clientIp_ = "";
    clientPort_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceSeril_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceName_ = s;
            break;
          }
          case 24: {

            deviceType_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceAddress_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceAccuracy_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceAccount_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            servicePassword_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            clientIp_ = s;
            break;
          }
          case 72: {

            clientPort_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ljzn.grpc.client.ClientMessageOuterClass.internal_static_PrisonSystem_ClientMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ljzn.grpc.client.ClientMessageOuterClass.internal_static_PrisonSystem_ClientMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ljzn.grpc.client.ClientMessage.class, com.ljzn.grpc.client.ClientMessage.Builder.class);
  }

  public static final int DEVICESERIL_FIELD_NUMBER = 1;
  private volatile java.lang.Object deviceSeril_;
  /**
   * <pre>
   *设备序列号       必填
   * </pre>
   *
   * <code>string deviceSeril = 1;</code>
   */
  public java.lang.String getDeviceSeril() {
    java.lang.Object ref = deviceSeril_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceSeril_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *设备序列号       必填
   * </pre>
   *
   * <code>string deviceSeril = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceSerilBytes() {
    java.lang.Object ref = deviceSeril_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceSeril_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object deviceName_;
  /**
   * <pre>
   *设备名称            必填
   * </pre>
   *
   * <code>string deviceName = 2;</code>
   */
  public java.lang.String getDeviceName() {
    java.lang.Object ref = deviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *设备名称            必填
   * </pre>
   *
   * <code>string deviceName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceNameBytes() {
    java.lang.Object ref = deviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICETYPE_FIELD_NUMBER = 3;
  private int deviceType_;
  /**
   * <pre>
   *设备类型      ( 1 大门闸机 2考勤机 3 访客机 4 人证机)    （监所项目选填)
   * </pre>
   *
   * <code>int32 deviceType = 3;</code>
   */
  public int getDeviceType() {
    return deviceType_;
  }

  public static final int DEVICEADDRESS_FIELD_NUMBER = 4;
  private volatile java.lang.Object deviceAddress_;
  /**
   * <pre>
   *设备地址   非必填
   * </pre>
   *
   * <code>string deviceAddress = 4;</code>
   */
  public java.lang.String getDeviceAddress() {
    java.lang.Object ref = deviceAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceAddress_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *设备地址   非必填
   * </pre>
   *
   * <code>string deviceAddress = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceAddressBytes() {
    java.lang.Object ref = deviceAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICEACCURACY_FIELD_NUMBER = 5;
  private volatile java.lang.Object deviceAccuracy_;
  /**
   * <pre>
   * 经纬度  非必填  格式{"longitude":"XXxx","latitude":"XXxx"}
   * </pre>
   *
   * <code>string deviceAccuracy = 5;</code>
   */
  public java.lang.String getDeviceAccuracy() {
    java.lang.Object ref = deviceAccuracy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceAccuracy_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 经纬度  非必填  格式{"longitude":"XXxx","latitude":"XXxx"}
   * </pre>
   *
   * <code>string deviceAccuracy = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceAccuracyBytes() {
    java.lang.Object ref = deviceAccuracy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceAccuracy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICEACCOUNT_FIELD_NUMBER = 6;
  private volatile java.lang.Object serviceAccount_;
  /**
   * <pre>
   * 所属服务账号名  必填
   * </pre>
   *
   * <code>string serviceAccount = 6;</code>
   */
  public java.lang.String getServiceAccount() {
    java.lang.Object ref = serviceAccount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceAccount_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 所属服务账号名  必填
   * </pre>
   *
   * <code>string serviceAccount = 6;</code>
   */
  public com.google.protobuf.ByteString
      getServiceAccountBytes() {
    java.lang.Object ref = serviceAccount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceAccount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICEPASSWORD_FIELD_NUMBER = 7;
  private volatile java.lang.Object servicePassword_;
  /**
   * <pre>
   *所属服务密码 必填
   * </pre>
   *
   * <code>string servicePassword = 7;</code>
   */
  public java.lang.String getServicePassword() {
    java.lang.Object ref = servicePassword_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      servicePassword_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *所属服务密码 必填
   * </pre>
   *
   * <code>string servicePassword = 7;</code>
   */
  public com.google.protobuf.ByteString
      getServicePasswordBytes() {
    java.lang.Object ref = servicePassword_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      servicePassword_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_IP_FIELD_NUMBER = 8;
  private volatile java.lang.Object clientIp_;
  /**
   * <pre>
   *客户端ip
   * </pre>
   *
   * <code>string client_ip = 8;</code>
   */
  public java.lang.String getClientIp() {
    java.lang.Object ref = clientIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientIp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *客户端ip
   * </pre>
   *
   * <code>string client_ip = 8;</code>
   */
  public com.google.protobuf.ByteString
      getClientIpBytes() {
    java.lang.Object ref = clientIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_PORT_FIELD_NUMBER = 9;
  private int clientPort_;
  /**
   * <pre>
   *客户端grpc端口
   * </pre>
   *
   * <code>int32 client_port = 9;</code>
   */
  public int getClientPort() {
    return clientPort_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDeviceSerilBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceSeril_);
    }
    if (!getDeviceNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceName_);
    }
    if (deviceType_ != 0) {
      output.writeInt32(3, deviceType_);
    }
    if (!getDeviceAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceAddress_);
    }
    if (!getDeviceAccuracyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, deviceAccuracy_);
    }
    if (!getServiceAccountBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, serviceAccount_);
    }
    if (!getServicePasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, servicePassword_);
    }
    if (!getClientIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, clientIp_);
    }
    if (clientPort_ != 0) {
      output.writeInt32(9, clientPort_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDeviceSerilBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceSeril_);
    }
    if (!getDeviceNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceName_);
    }
    if (deviceType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, deviceType_);
    }
    if (!getDeviceAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceAddress_);
    }
    if (!getDeviceAccuracyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, deviceAccuracy_);
    }
    if (!getServiceAccountBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, serviceAccount_);
    }
    if (!getServicePasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, servicePassword_);
    }
    if (!getClientIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, clientIp_);
    }
    if (clientPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, clientPort_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ljzn.grpc.client.ClientMessage)) {
      return super.equals(obj);
    }
    com.ljzn.grpc.client.ClientMessage other = (com.ljzn.grpc.client.ClientMessage) obj;

    boolean result = true;
    result = result && getDeviceSeril()
        .equals(other.getDeviceSeril());
    result = result && getDeviceName()
        .equals(other.getDeviceName());
    result = result && (getDeviceType()
        == other.getDeviceType());
    result = result && getDeviceAddress()
        .equals(other.getDeviceAddress());
    result = result && getDeviceAccuracy()
        .equals(other.getDeviceAccuracy());
    result = result && getServiceAccount()
        .equals(other.getServiceAccount());
    result = result && getServicePassword()
        .equals(other.getServicePassword());
    result = result && getClientIp()
        .equals(other.getClientIp());
    result = result && (getClientPort()
        == other.getClientPort());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEVICESERIL_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceSeril().hashCode();
    hash = (37 * hash) + DEVICENAME_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceName().hashCode();
    hash = (37 * hash) + DEVICETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceType();
    hash = (37 * hash) + DEVICEADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceAddress().hashCode();
    hash = (37 * hash) + DEVICEACCURACY_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceAccuracy().hashCode();
    hash = (37 * hash) + SERVICEACCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getServiceAccount().hashCode();
    hash = (37 * hash) + SERVICEPASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getServicePassword().hashCode();
    hash = (37 * hash) + CLIENT_IP_FIELD_NUMBER;
    hash = (53 * hash) + getClientIp().hashCode();
    hash = (37 * hash) + CLIENT_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getClientPort();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ljzn.grpc.client.ClientMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.client.ClientMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.client.ClientMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.client.ClientMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.client.ClientMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.client.ClientMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.client.ClientMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.client.ClientMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.client.ClientMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.client.ClientMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.client.ClientMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.client.ClientMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ljzn.grpc.client.ClientMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PrisonSystem.ClientMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PrisonSystem.ClientMessage)
      com.ljzn.grpc.client.ClientMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.client.ClientMessageOuterClass.internal_static_PrisonSystem_ClientMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.client.ClientMessageOuterClass.internal_static_PrisonSystem_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.client.ClientMessage.class, com.ljzn.grpc.client.ClientMessage.Builder.class);
    }

    // Construct using com.ljzn.grpc.client.ClientMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      deviceSeril_ = "";

      deviceName_ = "";

      deviceType_ = 0;

      deviceAddress_ = "";

      deviceAccuracy_ = "";

      serviceAccount_ = "";

      servicePassword_ = "";

      clientIp_ = "";

      clientPort_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ljzn.grpc.client.ClientMessageOuterClass.internal_static_PrisonSystem_ClientMessage_descriptor;
    }

    public com.ljzn.grpc.client.ClientMessage getDefaultInstanceForType() {
      return com.ljzn.grpc.client.ClientMessage.getDefaultInstance();
    }

    public com.ljzn.grpc.client.ClientMessage build() {
      com.ljzn.grpc.client.ClientMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ljzn.grpc.client.ClientMessage buildPartial() {
      com.ljzn.grpc.client.ClientMessage result = new com.ljzn.grpc.client.ClientMessage(this);
      result.deviceSeril_ = deviceSeril_;
      result.deviceName_ = deviceName_;
      result.deviceType_ = deviceType_;
      result.deviceAddress_ = deviceAddress_;
      result.deviceAccuracy_ = deviceAccuracy_;
      result.serviceAccount_ = serviceAccount_;
      result.servicePassword_ = servicePassword_;
      result.clientIp_ = clientIp_;
      result.clientPort_ = clientPort_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ljzn.grpc.client.ClientMessage) {
        return mergeFrom((com.ljzn.grpc.client.ClientMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ljzn.grpc.client.ClientMessage other) {
      if (other == com.ljzn.grpc.client.ClientMessage.getDefaultInstance()) return this;
      if (!other.getDeviceSeril().isEmpty()) {
        deviceSeril_ = other.deviceSeril_;
        onChanged();
      }
      if (!other.getDeviceName().isEmpty()) {
        deviceName_ = other.deviceName_;
        onChanged();
      }
      if (other.getDeviceType() != 0) {
        setDeviceType(other.getDeviceType());
      }
      if (!other.getDeviceAddress().isEmpty()) {
        deviceAddress_ = other.deviceAddress_;
        onChanged();
      }
      if (!other.getDeviceAccuracy().isEmpty()) {
        deviceAccuracy_ = other.deviceAccuracy_;
        onChanged();
      }
      if (!other.getServiceAccount().isEmpty()) {
        serviceAccount_ = other.serviceAccount_;
        onChanged();
      }
      if (!other.getServicePassword().isEmpty()) {
        servicePassword_ = other.servicePassword_;
        onChanged();
      }
      if (!other.getClientIp().isEmpty()) {
        clientIp_ = other.clientIp_;
        onChanged();
      }
      if (other.getClientPort() != 0) {
        setClientPort(other.getClientPort());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ljzn.grpc.client.ClientMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ljzn.grpc.client.ClientMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object deviceSeril_ = "";
    /**
     * <pre>
     *设备序列号       必填
     * </pre>
     *
     * <code>string deviceSeril = 1;</code>
     */
    public java.lang.String getDeviceSeril() {
      java.lang.Object ref = deviceSeril_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceSeril_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *设备序列号       必填
     * </pre>
     *
     * <code>string deviceSeril = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceSerilBytes() {
      java.lang.Object ref = deviceSeril_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceSeril_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *设备序列号       必填
     * </pre>
     *
     * <code>string deviceSeril = 1;</code>
     */
    public Builder setDeviceSeril(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceSeril_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备序列号       必填
     * </pre>
     *
     * <code>string deviceSeril = 1;</code>
     */
    public Builder clearDeviceSeril() {
      
      deviceSeril_ = getDefaultInstance().getDeviceSeril();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备序列号       必填
     * </pre>
     *
     * <code>string deviceSeril = 1;</code>
     */
    public Builder setDeviceSerilBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceSeril_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceName_ = "";
    /**
     * <pre>
     *设备名称            必填
     * </pre>
     *
     * <code>string deviceName = 2;</code>
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *设备名称            必填
     * </pre>
     *
     * <code>string deviceName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *设备名称            必填
     * </pre>
     *
     * <code>string deviceName = 2;</code>
     */
    public Builder setDeviceName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备名称            必填
     * </pre>
     *
     * <code>string deviceName = 2;</code>
     */
    public Builder clearDeviceName() {
      
      deviceName_ = getDefaultInstance().getDeviceName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备名称            必填
     * </pre>
     *
     * <code>string deviceName = 2;</code>
     */
    public Builder setDeviceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceName_ = value;
      onChanged();
      return this;
    }

    private int deviceType_ ;
    /**
     * <pre>
     *设备类型      ( 1 大门闸机 2考勤机 3 访客机 4 人证机)    （监所项目选填)
     * </pre>
     *
     * <code>int32 deviceType = 3;</code>
     */
    public int getDeviceType() {
      return deviceType_;
    }
    /**
     * <pre>
     *设备类型      ( 1 大门闸机 2考勤机 3 访客机 4 人证机)    （监所项目选填)
     * </pre>
     *
     * <code>int32 deviceType = 3;</code>
     */
    public Builder setDeviceType(int value) {
      
      deviceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备类型      ( 1 大门闸机 2考勤机 3 访客机 4 人证机)    （监所项目选填)
     * </pre>
     *
     * <code>int32 deviceType = 3;</code>
     */
    public Builder clearDeviceType() {
      
      deviceType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object deviceAddress_ = "";
    /**
     * <pre>
     *设备地址   非必填
     * </pre>
     *
     * <code>string deviceAddress = 4;</code>
     */
    public java.lang.String getDeviceAddress() {
      java.lang.Object ref = deviceAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *设备地址   非必填
     * </pre>
     *
     * <code>string deviceAddress = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceAddressBytes() {
      java.lang.Object ref = deviceAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *设备地址   非必填
     * </pre>
     *
     * <code>string deviceAddress = 4;</code>
     */
    public Builder setDeviceAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备地址   非必填
     * </pre>
     *
     * <code>string deviceAddress = 4;</code>
     */
    public Builder clearDeviceAddress() {
      
      deviceAddress_ = getDefaultInstance().getDeviceAddress();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备地址   非必填
     * </pre>
     *
     * <code>string deviceAddress = 4;</code>
     */
    public Builder setDeviceAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceAccuracy_ = "";
    /**
     * <pre>
     * 经纬度  非必填  格式{"longitude":"XXxx","latitude":"XXxx"}
     * </pre>
     *
     * <code>string deviceAccuracy = 5;</code>
     */
    public java.lang.String getDeviceAccuracy() {
      java.lang.Object ref = deviceAccuracy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceAccuracy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 经纬度  非必填  格式{"longitude":"XXxx","latitude":"XXxx"}
     * </pre>
     *
     * <code>string deviceAccuracy = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceAccuracyBytes() {
      java.lang.Object ref = deviceAccuracy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceAccuracy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 经纬度  非必填  格式{"longitude":"XXxx","latitude":"XXxx"}
     * </pre>
     *
     * <code>string deviceAccuracy = 5;</code>
     */
    public Builder setDeviceAccuracy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceAccuracy_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 经纬度  非必填  格式{"longitude":"XXxx","latitude":"XXxx"}
     * </pre>
     *
     * <code>string deviceAccuracy = 5;</code>
     */
    public Builder clearDeviceAccuracy() {
      
      deviceAccuracy_ = getDefaultInstance().getDeviceAccuracy();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 经纬度  非必填  格式{"longitude":"XXxx","latitude":"XXxx"}
     * </pre>
     *
     * <code>string deviceAccuracy = 5;</code>
     */
    public Builder setDeviceAccuracyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceAccuracy_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object serviceAccount_ = "";
    /**
     * <pre>
     * 所属服务账号名  必填
     * </pre>
     *
     * <code>string serviceAccount = 6;</code>
     */
    public java.lang.String getServiceAccount() {
      java.lang.Object ref = serviceAccount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceAccount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 所属服务账号名  必填
     * </pre>
     *
     * <code>string serviceAccount = 6;</code>
     */
    public com.google.protobuf.ByteString
        getServiceAccountBytes() {
      java.lang.Object ref = serviceAccount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 所属服务账号名  必填
     * </pre>
     *
     * <code>string serviceAccount = 6;</code>
     */
    public Builder setServiceAccount(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceAccount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 所属服务账号名  必填
     * </pre>
     *
     * <code>string serviceAccount = 6;</code>
     */
    public Builder clearServiceAccount() {
      
      serviceAccount_ = getDefaultInstance().getServiceAccount();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 所属服务账号名  必填
     * </pre>
     *
     * <code>string serviceAccount = 6;</code>
     */
    public Builder setServiceAccountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceAccount_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object servicePassword_ = "";
    /**
     * <pre>
     *所属服务密码 必填
     * </pre>
     *
     * <code>string servicePassword = 7;</code>
     */
    public java.lang.String getServicePassword() {
      java.lang.Object ref = servicePassword_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        servicePassword_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *所属服务密码 必填
     * </pre>
     *
     * <code>string servicePassword = 7;</code>
     */
    public com.google.protobuf.ByteString
        getServicePasswordBytes() {
      java.lang.Object ref = servicePassword_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        servicePassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *所属服务密码 必填
     * </pre>
     *
     * <code>string servicePassword = 7;</code>
     */
    public Builder setServicePassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      servicePassword_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *所属服务密码 必填
     * </pre>
     *
     * <code>string servicePassword = 7;</code>
     */
    public Builder clearServicePassword() {
      
      servicePassword_ = getDefaultInstance().getServicePassword();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *所属服务密码 必填
     * </pre>
     *
     * <code>string servicePassword = 7;</code>
     */
    public Builder setServicePasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      servicePassword_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object clientIp_ = "";
    /**
     * <pre>
     *客户端ip
     * </pre>
     *
     * <code>string client_ip = 8;</code>
     */
    public java.lang.String getClientIp() {
      java.lang.Object ref = clientIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *客户端ip
     * </pre>
     *
     * <code>string client_ip = 8;</code>
     */
    public com.google.protobuf.ByteString
        getClientIpBytes() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *客户端ip
     * </pre>
     *
     * <code>string client_ip = 8;</code>
     */
    public Builder setClientIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *客户端ip
     * </pre>
     *
     * <code>string client_ip = 8;</code>
     */
    public Builder clearClientIp() {
      
      clientIp_ = getDefaultInstance().getClientIp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *客户端ip
     * </pre>
     *
     * <code>string client_ip = 8;</code>
     */
    public Builder setClientIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientIp_ = value;
      onChanged();
      return this;
    }

    private int clientPort_ ;
    /**
     * <pre>
     *客户端grpc端口
     * </pre>
     *
     * <code>int32 client_port = 9;</code>
     */
    public int getClientPort() {
      return clientPort_;
    }
    /**
     * <pre>
     *客户端grpc端口
     * </pre>
     *
     * <code>int32 client_port = 9;</code>
     */
    public Builder setClientPort(int value) {
      
      clientPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *客户端grpc端口
     * </pre>
     *
     * <code>int32 client_port = 9;</code>
     */
    public Builder clearClientPort() {
      
      clientPort_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PrisonSystem.ClientMessage)
  }

  // @@protoc_insertion_point(class_scope:PrisonSystem.ClientMessage)
  private static final com.ljzn.grpc.client.ClientMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ljzn.grpc.client.ClientMessage();
  }

  public static com.ljzn.grpc.client.ClientMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientMessage>
      PARSER = new com.google.protobuf.AbstractParser<ClientMessage>() {
    public ClientMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientMessage> getParserForType() {
    return PARSER;
  }

  public com.ljzn.grpc.client.ClientMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

