// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/client.service.proto

package com.ljzn.grpc.client;

public interface HeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrisonSystem.HeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *设备序列号
   * </pre>
   *
   * <code>string deviceSeril = 1;</code>
   */
  java.lang.String getDeviceSeril();
  /**
   * <pre>
   *设备序列号
   * </pre>
   *
   * <code>string deviceSeril = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceSerilBytes();
}
