// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/client.service.proto

package com.ljzn.grpc.client;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrisonSystem.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *新平台统一GRPC接口返回码 成功为1 ,失败为-1)
   * </pre>
   *
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   *失败时为null
   * </pre>
   *
   * <code>string belongId = 3;</code>
   */
  java.lang.String getBelongId();
  /**
   * <pre>
   *失败时为null
   * </pre>
   *
   * <code>string belongId = 3;</code>
   */
  com.google.protobuf.ByteString
      getBelongIdBytes();
}
