// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/verify.service.proto

package com.ljzn.grpc.client;

/**
 * Protobuf type {@code ClientVerify.VerifyRequest}
 */
public  final class VerifyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ClientVerify.VerifyRequest)
    VerifyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VerifyRequest.newBuilder() to construct.
  private VerifyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VerifyRequest() {
    criminalId_ = "";
    delayTime_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VerifyRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            criminalId_ = s;
            break;
          }
          case 18: {
            com.ljzn.grpc.client.VerifyRequest.CriminalFeature.Builder subBuilder = null;
            if (feature_ != null) {
              subBuilder = feature_.toBuilder();
            }
            feature_ = input.readMessage(com.ljzn.grpc.client.VerifyRequest.CriminalFeature.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(feature_);
              feature_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            delayTime_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ljzn.grpc.client.VerifyServiceOuterClass.internal_static_ClientVerify_VerifyRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ljzn.grpc.client.VerifyServiceOuterClass.internal_static_ClientVerify_VerifyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ljzn.grpc.client.VerifyRequest.class, com.ljzn.grpc.client.VerifyRequest.Builder.class);
  }

  public interface CriminalFeatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientVerify.VerifyRequest.CriminalFeature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 len = 1;</code>
     */
    int getLen();

    /**
     * <code>repeated float data = 2;</code>
     */
    java.util.List<java.lang.Float> getDataList();
    /**
     * <code>repeated float data = 2;</code>
     */
    int getDataCount();
    /**
     * <code>repeated float data = 2;</code>
     */
    float getData(int index);
  }
  /**
   * Protobuf type {@code ClientVerify.VerifyRequest.CriminalFeature}
   */
  public  static final class CriminalFeature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientVerify.VerifyRequest.CriminalFeature)
      CriminalFeatureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CriminalFeature.newBuilder() to construct.
    private CriminalFeature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CriminalFeature() {
      len_ = 0;
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CriminalFeature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              len_ = input.readInt32();
              break;
            }
            case 21: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                data_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              data_.add(input.readFloat());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                data_ = new java.util.ArrayList<java.lang.Float>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                data_.add(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.client.VerifyServiceOuterClass.internal_static_ClientVerify_VerifyRequest_CriminalFeature_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.client.VerifyServiceOuterClass.internal_static_ClientVerify_VerifyRequest_CriminalFeature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.client.VerifyRequest.CriminalFeature.class, com.ljzn.grpc.client.VerifyRequest.CriminalFeature.Builder.class);
    }

    private int bitField0_;
    public static final int LEN_FIELD_NUMBER = 1;
    private int len_;
    /**
     * <code>int32 len = 1;</code>
     */
    public int getLen() {
      return len_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Float> data_;
    /**
     * <code>repeated float data = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated float data = 2;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated float data = 2;</code>
     */
    public float getData(int index) {
      return data_.get(index);
    }
    private int dataMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (len_ != 0) {
        output.writeInt32(1, len_);
      }
      if (getDataList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(dataMemoizedSerializedSize);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeFloatNoTag(data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (len_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, len_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getDataList().size();
        size += dataSize;
        if (!getDataList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        dataMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ljzn.grpc.client.VerifyRequest.CriminalFeature)) {
        return super.equals(obj);
      }
      com.ljzn.grpc.client.VerifyRequest.CriminalFeature other = (com.ljzn.grpc.client.VerifyRequest.CriminalFeature) obj;

      boolean result = true;
      result = result && (getLen()
          == other.getLen());
      result = result && getDataList()
          .equals(other.getDataList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LEN_FIELD_NUMBER;
      hash = (53 * hash) + getLen();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ljzn.grpc.client.VerifyRequest.CriminalFeature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientVerify.VerifyRequest.CriminalFeature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientVerify.VerifyRequest.CriminalFeature)
        com.ljzn.grpc.client.VerifyRequest.CriminalFeatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ljzn.grpc.client.VerifyServiceOuterClass.internal_static_ClientVerify_VerifyRequest_CriminalFeature_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ljzn.grpc.client.VerifyServiceOuterClass.internal_static_ClientVerify_VerifyRequest_CriminalFeature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ljzn.grpc.client.VerifyRequest.CriminalFeature.class, com.ljzn.grpc.client.VerifyRequest.CriminalFeature.Builder.class);
      }

      // Construct using com.ljzn.grpc.client.VerifyRequest.CriminalFeature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        len_ = 0;

        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ljzn.grpc.client.VerifyServiceOuterClass.internal_static_ClientVerify_VerifyRequest_CriminalFeature_descriptor;
      }

      public com.ljzn.grpc.client.VerifyRequest.CriminalFeature getDefaultInstanceForType() {
        return com.ljzn.grpc.client.VerifyRequest.CriminalFeature.getDefaultInstance();
      }

      public com.ljzn.grpc.client.VerifyRequest.CriminalFeature build() {
        com.ljzn.grpc.client.VerifyRequest.CriminalFeature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ljzn.grpc.client.VerifyRequest.CriminalFeature buildPartial() {
        com.ljzn.grpc.client.VerifyRequest.CriminalFeature result = new com.ljzn.grpc.client.VerifyRequest.CriminalFeature(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.len_ = len_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ljzn.grpc.client.VerifyRequest.CriminalFeature) {
          return mergeFrom((com.ljzn.grpc.client.VerifyRequest.CriminalFeature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ljzn.grpc.client.VerifyRequest.CriminalFeature other) {
        if (other == com.ljzn.grpc.client.VerifyRequest.CriminalFeature.getDefaultInstance()) return this;
        if (other.getLen() != 0) {
          setLen(other.getLen());
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ljzn.grpc.client.VerifyRequest.CriminalFeature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ljzn.grpc.client.VerifyRequest.CriminalFeature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int len_ ;
      /**
       * <code>int32 len = 1;</code>
       */
      public int getLen() {
        return len_;
      }
      /**
       * <code>int32 len = 1;</code>
       */
      public Builder setLen(int value) {
        
        len_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 len = 1;</code>
       */
      public Builder clearLen() {
        
        len_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Float> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          data_ = new java.util.ArrayList<java.lang.Float>(data_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated float data = 2;</code>
       */
      public java.util.List<java.lang.Float>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      /**
       * <code>repeated float data = 2;</code>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated float data = 2;</code>
       */
      public float getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated float data = 2;</code>
       */
      public Builder setData(
          int index, float value) {
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float data = 2;</code>
       */
      public Builder addData(float value) {
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float data = 2;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float data = 2;</code>
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientVerify.VerifyRequest.CriminalFeature)
    }

    // @@protoc_insertion_point(class_scope:ClientVerify.VerifyRequest.CriminalFeature)
    private static final com.ljzn.grpc.client.VerifyRequest.CriminalFeature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ljzn.grpc.client.VerifyRequest.CriminalFeature();
    }

    public static com.ljzn.grpc.client.VerifyRequest.CriminalFeature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CriminalFeature>
        PARSER = new com.google.protobuf.AbstractParser<CriminalFeature>() {
      public CriminalFeature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CriminalFeature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CriminalFeature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CriminalFeature> getParserForType() {
      return PARSER;
    }

    public com.ljzn.grpc.client.VerifyRequest.CriminalFeature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int CRIMINAL_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object criminalId_;
  /**
   * <pre>
   *罪犯id
   * </pre>
   *
   * <code>string criminal_id = 1;</code>
   */
  public java.lang.String getCriminalId() {
    java.lang.Object ref = criminalId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      criminalId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *罪犯id
   * </pre>
   *
   * <code>string criminal_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCriminalIdBytes() {
    java.lang.Object ref = criminalId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      criminalId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FEATURE_FIELD_NUMBER = 2;
  private com.ljzn.grpc.client.VerifyRequest.CriminalFeature feature_;
  /**
   * <pre>
   *罪犯特征
   * </pre>
   *
   * <code>.ClientVerify.VerifyRequest.CriminalFeature feature = 2;</code>
   */
  public boolean hasFeature() {
    return feature_ != null;
  }
  /**
   * <pre>
   *罪犯特征
   * </pre>
   *
   * <code>.ClientVerify.VerifyRequest.CriminalFeature feature = 2;</code>
   */
  public com.ljzn.grpc.client.VerifyRequest.CriminalFeature getFeature() {
    return feature_ == null ? com.ljzn.grpc.client.VerifyRequest.CriminalFeature.getDefaultInstance() : feature_;
  }
  /**
   * <pre>
   *罪犯特征
   * </pre>
   *
   * <code>.ClientVerify.VerifyRequest.CriminalFeature feature = 2;</code>
   */
  public com.ljzn.grpc.client.VerifyRequest.CriminalFeatureOrBuilder getFeatureOrBuilder() {
    return getFeature();
  }

  public static final int DELAY_TIME_FIELD_NUMBER = 3;
  private int delayTime_;
  /**
   * <pre>
   *超时时间(秒)
   * </pre>
   *
   * <code>int32 delay_time = 3;</code>
   */
  public int getDelayTime() {
    return delayTime_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCriminalIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, criminalId_);
    }
    if (feature_ != null) {
      output.writeMessage(2, getFeature());
    }
    if (delayTime_ != 0) {
      output.writeInt32(3, delayTime_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCriminalIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, criminalId_);
    }
    if (feature_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFeature());
    }
    if (delayTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, delayTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ljzn.grpc.client.VerifyRequest)) {
      return super.equals(obj);
    }
    com.ljzn.grpc.client.VerifyRequest other = (com.ljzn.grpc.client.VerifyRequest) obj;

    boolean result = true;
    result = result && getCriminalId()
        .equals(other.getCriminalId());
    result = result && (hasFeature() == other.hasFeature());
    if (hasFeature()) {
      result = result && getFeature()
          .equals(other.getFeature());
    }
    result = result && (getDelayTime()
        == other.getDelayTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CRIMINAL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCriminalId().hashCode();
    if (hasFeature()) {
      hash = (37 * hash) + FEATURE_FIELD_NUMBER;
      hash = (53 * hash) + getFeature().hashCode();
    }
    hash = (37 * hash) + DELAY_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getDelayTime();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ljzn.grpc.client.VerifyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.client.VerifyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.client.VerifyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.client.VerifyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.client.VerifyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.client.VerifyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.client.VerifyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.client.VerifyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.client.VerifyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.client.VerifyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.client.VerifyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.client.VerifyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ljzn.grpc.client.VerifyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ClientVerify.VerifyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ClientVerify.VerifyRequest)
      com.ljzn.grpc.client.VerifyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.client.VerifyServiceOuterClass.internal_static_ClientVerify_VerifyRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.client.VerifyServiceOuterClass.internal_static_ClientVerify_VerifyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.client.VerifyRequest.class, com.ljzn.grpc.client.VerifyRequest.Builder.class);
    }

    // Construct using com.ljzn.grpc.client.VerifyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      criminalId_ = "";

      if (featureBuilder_ == null) {
        feature_ = null;
      } else {
        feature_ = null;
        featureBuilder_ = null;
      }
      delayTime_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ljzn.grpc.client.VerifyServiceOuterClass.internal_static_ClientVerify_VerifyRequest_descriptor;
    }

    public com.ljzn.grpc.client.VerifyRequest getDefaultInstanceForType() {
      return com.ljzn.grpc.client.VerifyRequest.getDefaultInstance();
    }

    public com.ljzn.grpc.client.VerifyRequest build() {
      com.ljzn.grpc.client.VerifyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ljzn.grpc.client.VerifyRequest buildPartial() {
      com.ljzn.grpc.client.VerifyRequest result = new com.ljzn.grpc.client.VerifyRequest(this);
      result.criminalId_ = criminalId_;
      if (featureBuilder_ == null) {
        result.feature_ = feature_;
      } else {
        result.feature_ = featureBuilder_.build();
      }
      result.delayTime_ = delayTime_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ljzn.grpc.client.VerifyRequest) {
        return mergeFrom((com.ljzn.grpc.client.VerifyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ljzn.grpc.client.VerifyRequest other) {
      if (other == com.ljzn.grpc.client.VerifyRequest.getDefaultInstance()) return this;
      if (!other.getCriminalId().isEmpty()) {
        criminalId_ = other.criminalId_;
        onChanged();
      }
      if (other.hasFeature()) {
        mergeFeature(other.getFeature());
      }
      if (other.getDelayTime() != 0) {
        setDelayTime(other.getDelayTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ljzn.grpc.client.VerifyRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ljzn.grpc.client.VerifyRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object criminalId_ = "";
    /**
     * <pre>
     *罪犯id
     * </pre>
     *
     * <code>string criminal_id = 1;</code>
     */
    public java.lang.String getCriminalId() {
      java.lang.Object ref = criminalId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        criminalId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *罪犯id
     * </pre>
     *
     * <code>string criminal_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCriminalIdBytes() {
      java.lang.Object ref = criminalId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        criminalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *罪犯id
     * </pre>
     *
     * <code>string criminal_id = 1;</code>
     */
    public Builder setCriminalId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      criminalId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *罪犯id
     * </pre>
     *
     * <code>string criminal_id = 1;</code>
     */
    public Builder clearCriminalId() {
      
      criminalId_ = getDefaultInstance().getCriminalId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *罪犯id
     * </pre>
     *
     * <code>string criminal_id = 1;</code>
     */
    public Builder setCriminalIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      criminalId_ = value;
      onChanged();
      return this;
    }

    private com.ljzn.grpc.client.VerifyRequest.CriminalFeature feature_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ljzn.grpc.client.VerifyRequest.CriminalFeature, com.ljzn.grpc.client.VerifyRequest.CriminalFeature.Builder, com.ljzn.grpc.client.VerifyRequest.CriminalFeatureOrBuilder> featureBuilder_;
    /**
     * <pre>
     *罪犯特征
     * </pre>
     *
     * <code>.ClientVerify.VerifyRequest.CriminalFeature feature = 2;</code>
     */
    public boolean hasFeature() {
      return featureBuilder_ != null || feature_ != null;
    }
    /**
     * <pre>
     *罪犯特征
     * </pre>
     *
     * <code>.ClientVerify.VerifyRequest.CriminalFeature feature = 2;</code>
     */
    public com.ljzn.grpc.client.VerifyRequest.CriminalFeature getFeature() {
      if (featureBuilder_ == null) {
        return feature_ == null ? com.ljzn.grpc.client.VerifyRequest.CriminalFeature.getDefaultInstance() : feature_;
      } else {
        return featureBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *罪犯特征
     * </pre>
     *
     * <code>.ClientVerify.VerifyRequest.CriminalFeature feature = 2;</code>
     */
    public Builder setFeature(com.ljzn.grpc.client.VerifyRequest.CriminalFeature value) {
      if (featureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        feature_ = value;
        onChanged();
      } else {
        featureBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *罪犯特征
     * </pre>
     *
     * <code>.ClientVerify.VerifyRequest.CriminalFeature feature = 2;</code>
     */
    public Builder setFeature(
        com.ljzn.grpc.client.VerifyRequest.CriminalFeature.Builder builderForValue) {
      if (featureBuilder_ == null) {
        feature_ = builderForValue.build();
        onChanged();
      } else {
        featureBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *罪犯特征
     * </pre>
     *
     * <code>.ClientVerify.VerifyRequest.CriminalFeature feature = 2;</code>
     */
    public Builder mergeFeature(com.ljzn.grpc.client.VerifyRequest.CriminalFeature value) {
      if (featureBuilder_ == null) {
        if (feature_ != null) {
          feature_ =
            com.ljzn.grpc.client.VerifyRequest.CriminalFeature.newBuilder(feature_).mergeFrom(value).buildPartial();
        } else {
          feature_ = value;
        }
        onChanged();
      } else {
        featureBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *罪犯特征
     * </pre>
     *
     * <code>.ClientVerify.VerifyRequest.CriminalFeature feature = 2;</code>
     */
    public Builder clearFeature() {
      if (featureBuilder_ == null) {
        feature_ = null;
        onChanged();
      } else {
        feature_ = null;
        featureBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *罪犯特征
     * </pre>
     *
     * <code>.ClientVerify.VerifyRequest.CriminalFeature feature = 2;</code>
     */
    public com.ljzn.grpc.client.VerifyRequest.CriminalFeature.Builder getFeatureBuilder() {
      
      onChanged();
      return getFeatureFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *罪犯特征
     * </pre>
     *
     * <code>.ClientVerify.VerifyRequest.CriminalFeature feature = 2;</code>
     */
    public com.ljzn.grpc.client.VerifyRequest.CriminalFeatureOrBuilder getFeatureOrBuilder() {
      if (featureBuilder_ != null) {
        return featureBuilder_.getMessageOrBuilder();
      } else {
        return feature_ == null ?
            com.ljzn.grpc.client.VerifyRequest.CriminalFeature.getDefaultInstance() : feature_;
      }
    }
    /**
     * <pre>
     *罪犯特征
     * </pre>
     *
     * <code>.ClientVerify.VerifyRequest.CriminalFeature feature = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ljzn.grpc.client.VerifyRequest.CriminalFeature, com.ljzn.grpc.client.VerifyRequest.CriminalFeature.Builder, com.ljzn.grpc.client.VerifyRequest.CriminalFeatureOrBuilder> 
        getFeatureFieldBuilder() {
      if (featureBuilder_ == null) {
        featureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ljzn.grpc.client.VerifyRequest.CriminalFeature, com.ljzn.grpc.client.VerifyRequest.CriminalFeature.Builder, com.ljzn.grpc.client.VerifyRequest.CriminalFeatureOrBuilder>(
                getFeature(),
                getParentForChildren(),
                isClean());
        feature_ = null;
      }
      return featureBuilder_;
    }

    private int delayTime_ ;
    /**
     * <pre>
     *超时时间(秒)
     * </pre>
     *
     * <code>int32 delay_time = 3;</code>
     */
    public int getDelayTime() {
      return delayTime_;
    }
    /**
     * <pre>
     *超时时间(秒)
     * </pre>
     *
     * <code>int32 delay_time = 3;</code>
     */
    public Builder setDelayTime(int value) {
      
      delayTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *超时时间(秒)
     * </pre>
     *
     * <code>int32 delay_time = 3;</code>
     */
    public Builder clearDelayTime() {
      
      delayTime_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ClientVerify.VerifyRequest)
  }

  // @@protoc_insertion_point(class_scope:ClientVerify.VerifyRequest)
  private static final com.ljzn.grpc.client.VerifyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ljzn.grpc.client.VerifyRequest();
  }

  public static com.ljzn.grpc.client.VerifyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerifyRequest>
      PARSER = new com.google.protobuf.AbstractParser<VerifyRequest>() {
    public VerifyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new VerifyRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VerifyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VerifyRequest> getParserForType() {
    return PARSER;
  }

  public com.ljzn.grpc.client.VerifyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

