// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client/verify.service.proto

package com.ljzn.grpc.client;

public interface VerifyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientVerify.VerifyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *成功=1,其他失败
   * </pre>
   *
   * <code>int32 result = 1;</code>
   */
  int getResult();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>float score = 3;</code>
   */
  float getScore();

  /**
   * <code>int64 verify_time = 4;</code>
   */
  long getVerifyTime();

  /**
   * <code>bytes photo = 5;</code>
   */
  com.google.protobuf.ByteString getPhoto();
}
