server:
  port: 8080
grpc:
  server:
    port: 8087
spring:
  datasource:
    name: te
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wisdom_site?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: jian
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  resources:
    static-locations: classpath:/static/,classpath:upload/images/,file:D:/upload,file:www/dist
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath*:com/jian/dao/mapper/*.xml
  
recordUpload: http://saas.weyouedu.com/api/record/upload
configPort: 10001
dataPort: 10002