// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.service.proto

package com.ljzn.grpc.personinfo;

public interface PersoninfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrisonSystem.PersoninfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *新平台统一GRPC接口返回码 成功为1 ,失败为-1)
   * </pre>
   *
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
   */
  java.util.List<com.ljzn.grpc.personinfo.PersoninfoMessage> 
      getPersonInfoList();
  /**
   * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
   */
  com.ljzn.grpc.personinfo.PersoninfoMessage getPersonInfo(int index);
  /**
   * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
   */
  int getPersonInfoCount();
  /**
   * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
   */
  java.util.List<? extends com.ljzn.grpc.personinfo.PersoninfoMessageOrBuilder> 
      getPersonInfoOrBuilderList();
  /**
   * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
   */
  com.ljzn.grpc.personinfo.PersoninfoMessageOrBuilder getPersonInfoOrBuilder(
      int index);
}
