// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.service.proto

package com.ljzn.grpc.personinfo;

/**
 * Protobuf type {@code PrisonSystem.PersoninfoResponse}
 */
public  final class PersoninfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PrisonSystem.PersoninfoResponse)
    PersoninfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PersoninfoResponse.newBuilder() to construct.
  private PersoninfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersoninfoResponse() {
    code_ = 0;
    message_ = "";
    personInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PersoninfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            code_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              personInfo_ = new java.util.ArrayList<com.ljzn.grpc.personinfo.PersoninfoMessage>();
              mutable_bitField0_ |= 0x00000004;
            }
            personInfo_.add(
                input.readMessage(com.ljzn.grpc.personinfo.PersoninfoMessage.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        personInfo_ = java.util.Collections.unmodifiableList(personInfo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_PersoninfoResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_PersoninfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ljzn.grpc.personinfo.PersoninfoResponse.class, com.ljzn.grpc.personinfo.PersoninfoResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <pre>
   *新平台统一GRPC接口返回码 成功为1 ,失败为-1)
   * </pre>
   *
   * <code>int32 code = 1;</code>
   */
  public int getCode() {
    return code_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERSONINFO_FIELD_NUMBER = 3;
  private java.util.List<com.ljzn.grpc.personinfo.PersoninfoMessage> personInfo_;
  /**
   * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
   */
  public java.util.List<com.ljzn.grpc.personinfo.PersoninfoMessage> getPersonInfoList() {
    return personInfo_;
  }
  /**
   * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
   */
  public java.util.List<? extends com.ljzn.grpc.personinfo.PersoninfoMessageOrBuilder> 
      getPersonInfoOrBuilderList() {
    return personInfo_;
  }
  /**
   * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
   */
  public int getPersonInfoCount() {
    return personInfo_.size();
  }
  /**
   * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
   */
  public com.ljzn.grpc.personinfo.PersoninfoMessage getPersonInfo(int index) {
    return personInfo_.get(index);
  }
  /**
   * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
   */
  public com.ljzn.grpc.personinfo.PersoninfoMessageOrBuilder getPersonInfoOrBuilder(
      int index) {
    return personInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < personInfo_.size(); i++) {
      output.writeMessage(3, personInfo_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    for (int i = 0; i < personInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, personInfo_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ljzn.grpc.personinfo.PersoninfoResponse)) {
      return super.equals(obj);
    }
    com.ljzn.grpc.personinfo.PersoninfoResponse other = (com.ljzn.grpc.personinfo.PersoninfoResponse) obj;

    boolean result = true;
    result = result && (getCode()
        == other.getCode());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getPersonInfoList()
        .equals(other.getPersonInfoList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getPersonInfoCount() > 0) {
      hash = (37 * hash) + PERSONINFO_FIELD_NUMBER;
      hash = (53 * hash) + getPersonInfoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ljzn.grpc.personinfo.PersoninfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ljzn.grpc.personinfo.PersoninfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PrisonSystem.PersoninfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PrisonSystem.PersoninfoResponse)
      com.ljzn.grpc.personinfo.PersoninfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_PersoninfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_PersoninfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.personinfo.PersoninfoResponse.class, com.ljzn.grpc.personinfo.PersoninfoResponse.Builder.class);
    }

    // Construct using com.ljzn.grpc.personinfo.PersoninfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPersonInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      code_ = 0;

      message_ = "";

      if (personInfoBuilder_ == null) {
        personInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        personInfoBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_PersoninfoResponse_descriptor;
    }

    public com.ljzn.grpc.personinfo.PersoninfoResponse getDefaultInstanceForType() {
      return com.ljzn.grpc.personinfo.PersoninfoResponse.getDefaultInstance();
    }

    public com.ljzn.grpc.personinfo.PersoninfoResponse build() {
      com.ljzn.grpc.personinfo.PersoninfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ljzn.grpc.personinfo.PersoninfoResponse buildPartial() {
      com.ljzn.grpc.personinfo.PersoninfoResponse result = new com.ljzn.grpc.personinfo.PersoninfoResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.code_ = code_;
      result.message_ = message_;
      if (personInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          personInfo_ = java.util.Collections.unmodifiableList(personInfo_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.personInfo_ = personInfo_;
      } else {
        result.personInfo_ = personInfoBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ljzn.grpc.personinfo.PersoninfoResponse) {
        return mergeFrom((com.ljzn.grpc.personinfo.PersoninfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ljzn.grpc.personinfo.PersoninfoResponse other) {
      if (other == com.ljzn.grpc.personinfo.PersoninfoResponse.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (personInfoBuilder_ == null) {
        if (!other.personInfo_.isEmpty()) {
          if (personInfo_.isEmpty()) {
            personInfo_ = other.personInfo_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePersonInfoIsMutable();
            personInfo_.addAll(other.personInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.personInfo_.isEmpty()) {
          if (personInfoBuilder_.isEmpty()) {
            personInfoBuilder_.dispose();
            personInfoBuilder_ = null;
            personInfo_ = other.personInfo_;
            bitField0_ = (bitField0_ & ~0x00000004);
            personInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPersonInfoFieldBuilder() : null;
          } else {
            personInfoBuilder_.addAllMessages(other.personInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ljzn.grpc.personinfo.PersoninfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ljzn.grpc.personinfo.PersoninfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int code_ ;
    /**
     * <pre>
     *新平台统一GRPC接口返回码 成功为1 ,失败为-1)
     * </pre>
     *
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <pre>
     *新平台统一GRPC接口返回码 成功为1 ,失败为-1)
     * </pre>
     *
     * <code>int32 code = 1;</code>
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *新平台统一GRPC接口返回码 成功为1 ,失败为-1)
     * </pre>
     *
     * <code>int32 code = 1;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.ljzn.grpc.personinfo.PersoninfoMessage> personInfo_ =
      java.util.Collections.emptyList();
    private void ensurePersonInfoIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        personInfo_ = new java.util.ArrayList<com.ljzn.grpc.personinfo.PersoninfoMessage>(personInfo_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ljzn.grpc.personinfo.PersoninfoMessage, com.ljzn.grpc.personinfo.PersoninfoMessage.Builder, com.ljzn.grpc.personinfo.PersoninfoMessageOrBuilder> personInfoBuilder_;

    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public java.util.List<com.ljzn.grpc.personinfo.PersoninfoMessage> getPersonInfoList() {
      if (personInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(personInfo_);
      } else {
        return personInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public int getPersonInfoCount() {
      if (personInfoBuilder_ == null) {
        return personInfo_.size();
      } else {
        return personInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public com.ljzn.grpc.personinfo.PersoninfoMessage getPersonInfo(int index) {
      if (personInfoBuilder_ == null) {
        return personInfo_.get(index);
      } else {
        return personInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public Builder setPersonInfo(
        int index, com.ljzn.grpc.personinfo.PersoninfoMessage value) {
      if (personInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonInfoIsMutable();
        personInfo_.set(index, value);
        onChanged();
      } else {
        personInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public Builder setPersonInfo(
        int index, com.ljzn.grpc.personinfo.PersoninfoMessage.Builder builderForValue) {
      if (personInfoBuilder_ == null) {
        ensurePersonInfoIsMutable();
        personInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        personInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public Builder addPersonInfo(com.ljzn.grpc.personinfo.PersoninfoMessage value) {
      if (personInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonInfoIsMutable();
        personInfo_.add(value);
        onChanged();
      } else {
        personInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public Builder addPersonInfo(
        int index, com.ljzn.grpc.personinfo.PersoninfoMessage value) {
      if (personInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonInfoIsMutable();
        personInfo_.add(index, value);
        onChanged();
      } else {
        personInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public Builder addPersonInfo(
        com.ljzn.grpc.personinfo.PersoninfoMessage.Builder builderForValue) {
      if (personInfoBuilder_ == null) {
        ensurePersonInfoIsMutable();
        personInfo_.add(builderForValue.build());
        onChanged();
      } else {
        personInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public Builder addPersonInfo(
        int index, com.ljzn.grpc.personinfo.PersoninfoMessage.Builder builderForValue) {
      if (personInfoBuilder_ == null) {
        ensurePersonInfoIsMutable();
        personInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        personInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public Builder addAllPersonInfo(
        java.lang.Iterable<? extends com.ljzn.grpc.personinfo.PersoninfoMessage> values) {
      if (personInfoBuilder_ == null) {
        ensurePersonInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, personInfo_);
        onChanged();
      } else {
        personInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public Builder clearPersonInfo() {
      if (personInfoBuilder_ == null) {
        personInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        personInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public Builder removePersonInfo(int index) {
      if (personInfoBuilder_ == null) {
        ensurePersonInfoIsMutable();
        personInfo_.remove(index);
        onChanged();
      } else {
        personInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public com.ljzn.grpc.personinfo.PersoninfoMessage.Builder getPersonInfoBuilder(
        int index) {
      return getPersonInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public com.ljzn.grpc.personinfo.PersoninfoMessageOrBuilder getPersonInfoOrBuilder(
        int index) {
      if (personInfoBuilder_ == null) {
        return personInfo_.get(index);  } else {
        return personInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public java.util.List<? extends com.ljzn.grpc.personinfo.PersoninfoMessageOrBuilder> 
         getPersonInfoOrBuilderList() {
      if (personInfoBuilder_ != null) {
        return personInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(personInfo_);
      }
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public com.ljzn.grpc.personinfo.PersoninfoMessage.Builder addPersonInfoBuilder() {
      return getPersonInfoFieldBuilder().addBuilder(
          com.ljzn.grpc.personinfo.PersoninfoMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public com.ljzn.grpc.personinfo.PersoninfoMessage.Builder addPersonInfoBuilder(
        int index) {
      return getPersonInfoFieldBuilder().addBuilder(
          index, com.ljzn.grpc.personinfo.PersoninfoMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .PrisonSystem.PersoninfoMessage personInfo = 3;</code>
     */
    public java.util.List<com.ljzn.grpc.personinfo.PersoninfoMessage.Builder> 
         getPersonInfoBuilderList() {
      return getPersonInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ljzn.grpc.personinfo.PersoninfoMessage, com.ljzn.grpc.personinfo.PersoninfoMessage.Builder, com.ljzn.grpc.personinfo.PersoninfoMessageOrBuilder> 
        getPersonInfoFieldBuilder() {
      if (personInfoBuilder_ == null) {
        personInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ljzn.grpc.personinfo.PersoninfoMessage, com.ljzn.grpc.personinfo.PersoninfoMessage.Builder, com.ljzn.grpc.personinfo.PersoninfoMessageOrBuilder>(
                personInfo_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        personInfo_ = null;
      }
      return personInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PrisonSystem.PersoninfoResponse)
  }

  // @@protoc_insertion_point(class_scope:PrisonSystem.PersoninfoResponse)
  private static final com.ljzn.grpc.personinfo.PersoninfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ljzn.grpc.personinfo.PersoninfoResponse();
  }

  public static com.ljzn.grpc.personinfo.PersoninfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersoninfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<PersoninfoResponse>() {
    public PersoninfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PersoninfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PersoninfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersoninfoResponse> getParserForType() {
    return PARSER;
  }

  public com.ljzn.grpc.personinfo.PersoninfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

