// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.service.proto

package com.ljzn.grpc.personinfo;

/**
 * <pre>
 *获取人员数据
 * </pre>
 *
 * Protobuf type {@code PrisonSystem.PersoninfoRequest}
 */
public  final class PersoninfoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PrisonSystem.PersoninfoRequest)
    PersoninfoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PersoninfoRequest.newBuilder() to construct.
  private PersoninfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersoninfoRequest() {
    version_ = 0L;
    needPhoto_ = false;
    belongId_ = "";
    persontype_ = 0;
    deviceSeril_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PersoninfoRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            version_ = input.readInt64();
            break;
          }
          case 16: {

            needPhoto_ = input.readBool();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            belongId_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            persontype_ = rawValue;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceSeril_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_PersoninfoRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_PersoninfoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ljzn.grpc.personinfo.PersoninfoRequest.class, com.ljzn.grpc.personinfo.PersoninfoRequest.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private long version_;
  /**
   * <pre>
   *软件启动时上传的version值是0,然后服务端会返回全部数据 
   * </pre>
   *
   * <code>int64 version = 1;</code>
   */
  public long getVersion() {
    return version_;
  }

  public static final int NEEDPHOTO_FIELD_NUMBER = 2;
  private boolean needPhoto_;
  /**
   * <pre>
   *false不需要 true 须要
   * </pre>
   *
   * <code>bool needPhoto = 2;</code>
   */
  public boolean getNeedPhoto() {
    return needPhoto_;
  }

  public static final int BELONGID_FIELD_NUMBER = 3;
  private volatile java.lang.Object belongId_;
  /**
   * <code>string belongId = 3;</code>
   */
  public java.lang.String getBelongId() {
    java.lang.Object ref = belongId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      belongId_ = s;
      return s;
    }
  }
  /**
   * <code>string belongId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBelongIdBytes() {
    java.lang.Object ref = belongId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      belongId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERSONTYPE_FIELD_NUMBER = 4;
  private int persontype_;
  /**
   * <pre>
   *人员类型
   * </pre>
   *
   * <code>.PrisonSystem.PersonType persontype = 4;</code>
   */
  public int getPersontypeValue() {
    return persontype_;
  }
  /**
   * <pre>
   *人员类型
   * </pre>
   *
   * <code>.PrisonSystem.PersonType persontype = 4;</code>
   */
  public com.ljzn.grpc.personinfo.PersonType getPersontype() {
    com.ljzn.grpc.personinfo.PersonType result = com.ljzn.grpc.personinfo.PersonType.valueOf(persontype_);
    return result == null ? com.ljzn.grpc.personinfo.PersonType.UNRECOGNIZED : result;
  }

  public static final int DEVICESERIL_FIELD_NUMBER = 5;
  private volatile java.lang.Object deviceSeril_;
  /**
   * <code>string deviceSeril = 5;</code>
   */
  public java.lang.String getDeviceSeril() {
    java.lang.Object ref = deviceSeril_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceSeril_ = s;
      return s;
    }
  }
  /**
   * <code>string deviceSeril = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceSerilBytes() {
    java.lang.Object ref = deviceSeril_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceSeril_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0L) {
      output.writeInt64(1, version_);
    }
    if (needPhoto_ != false) {
      output.writeBool(2, needPhoto_);
    }
    if (!getBelongIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, belongId_);
    }
    if (persontype_ != com.ljzn.grpc.personinfo.PersonType.Police.getNumber()) {
      output.writeEnum(4, persontype_);
    }
    if (!getDeviceSerilBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, deviceSeril_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, version_);
    }
    if (needPhoto_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, needPhoto_);
    }
    if (!getBelongIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, belongId_);
    }
    if (persontype_ != com.ljzn.grpc.personinfo.PersonType.Police.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, persontype_);
    }
    if (!getDeviceSerilBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, deviceSeril_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ljzn.grpc.personinfo.PersoninfoRequest)) {
      return super.equals(obj);
    }
    com.ljzn.grpc.personinfo.PersoninfoRequest other = (com.ljzn.grpc.personinfo.PersoninfoRequest) obj;

    boolean result = true;
    result = result && (getVersion()
        == other.getVersion());
    result = result && (getNeedPhoto()
        == other.getNeedPhoto());
    result = result && getBelongId()
        .equals(other.getBelongId());
    result = result && persontype_ == other.persontype_;
    result = result && getDeviceSeril()
        .equals(other.getDeviceSeril());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVersion());
    hash = (37 * hash) + NEEDPHOTO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNeedPhoto());
    hash = (37 * hash) + BELONGID_FIELD_NUMBER;
    hash = (53 * hash) + getBelongId().hashCode();
    hash = (37 * hash) + PERSONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + persontype_;
    hash = (37 * hash) + DEVICESERIL_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceSeril().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ljzn.grpc.personinfo.PersoninfoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ljzn.grpc.personinfo.PersoninfoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *获取人员数据
   * </pre>
   *
   * Protobuf type {@code PrisonSystem.PersoninfoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PrisonSystem.PersoninfoRequest)
      com.ljzn.grpc.personinfo.PersoninfoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_PersoninfoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_PersoninfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.personinfo.PersoninfoRequest.class, com.ljzn.grpc.personinfo.PersoninfoRequest.Builder.class);
    }

    // Construct using com.ljzn.grpc.personinfo.PersoninfoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      version_ = 0L;

      needPhoto_ = false;

      belongId_ = "";

      persontype_ = 0;

      deviceSeril_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_PersoninfoRequest_descriptor;
    }

    public com.ljzn.grpc.personinfo.PersoninfoRequest getDefaultInstanceForType() {
      return com.ljzn.grpc.personinfo.PersoninfoRequest.getDefaultInstance();
    }

    public com.ljzn.grpc.personinfo.PersoninfoRequest build() {
      com.ljzn.grpc.personinfo.PersoninfoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ljzn.grpc.personinfo.PersoninfoRequest buildPartial() {
      com.ljzn.grpc.personinfo.PersoninfoRequest result = new com.ljzn.grpc.personinfo.PersoninfoRequest(this);
      result.version_ = version_;
      result.needPhoto_ = needPhoto_;
      result.belongId_ = belongId_;
      result.persontype_ = persontype_;
      result.deviceSeril_ = deviceSeril_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ljzn.grpc.personinfo.PersoninfoRequest) {
        return mergeFrom((com.ljzn.grpc.personinfo.PersoninfoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ljzn.grpc.personinfo.PersoninfoRequest other) {
      if (other == com.ljzn.grpc.personinfo.PersoninfoRequest.getDefaultInstance()) return this;
      if (other.getVersion() != 0L) {
        setVersion(other.getVersion());
      }
      if (other.getNeedPhoto() != false) {
        setNeedPhoto(other.getNeedPhoto());
      }
      if (!other.getBelongId().isEmpty()) {
        belongId_ = other.belongId_;
        onChanged();
      }
      if (other.persontype_ != 0) {
        setPersontypeValue(other.getPersontypeValue());
      }
      if (!other.getDeviceSeril().isEmpty()) {
        deviceSeril_ = other.deviceSeril_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ljzn.grpc.personinfo.PersoninfoRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ljzn.grpc.personinfo.PersoninfoRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long version_ ;
    /**
     * <pre>
     *软件启动时上传的version值是0,然后服务端会返回全部数据 
     * </pre>
     *
     * <code>int64 version = 1;</code>
     */
    public long getVersion() {
      return version_;
    }
    /**
     * <pre>
     *软件启动时上传的version值是0,然后服务端会返回全部数据 
     * </pre>
     *
     * <code>int64 version = 1;</code>
     */
    public Builder setVersion(long value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *软件启动时上传的version值是0,然后服务端会返回全部数据 
     * </pre>
     *
     * <code>int64 version = 1;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0L;
      onChanged();
      return this;
    }

    private boolean needPhoto_ ;
    /**
     * <pre>
     *false不需要 true 须要
     * </pre>
     *
     * <code>bool needPhoto = 2;</code>
     */
    public boolean getNeedPhoto() {
      return needPhoto_;
    }
    /**
     * <pre>
     *false不需要 true 须要
     * </pre>
     *
     * <code>bool needPhoto = 2;</code>
     */
    public Builder setNeedPhoto(boolean value) {
      
      needPhoto_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *false不需要 true 须要
     * </pre>
     *
     * <code>bool needPhoto = 2;</code>
     */
    public Builder clearNeedPhoto() {
      
      needPhoto_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object belongId_ = "";
    /**
     * <code>string belongId = 3;</code>
     */
    public java.lang.String getBelongId() {
      java.lang.Object ref = belongId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        belongId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string belongId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBelongIdBytes() {
      java.lang.Object ref = belongId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        belongId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string belongId = 3;</code>
     */
    public Builder setBelongId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      belongId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string belongId = 3;</code>
     */
    public Builder clearBelongId() {
      
      belongId_ = getDefaultInstance().getBelongId();
      onChanged();
      return this;
    }
    /**
     * <code>string belongId = 3;</code>
     */
    public Builder setBelongIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      belongId_ = value;
      onChanged();
      return this;
    }

    private int persontype_ = 0;
    /**
     * <pre>
     *人员类型
     * </pre>
     *
     * <code>.PrisonSystem.PersonType persontype = 4;</code>
     */
    public int getPersontypeValue() {
      return persontype_;
    }
    /**
     * <pre>
     *人员类型
     * </pre>
     *
     * <code>.PrisonSystem.PersonType persontype = 4;</code>
     */
    public Builder setPersontypeValue(int value) {
      persontype_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *人员类型
     * </pre>
     *
     * <code>.PrisonSystem.PersonType persontype = 4;</code>
     */
    public com.ljzn.grpc.personinfo.PersonType getPersontype() {
      com.ljzn.grpc.personinfo.PersonType result = com.ljzn.grpc.personinfo.PersonType.valueOf(persontype_);
      return result == null ? com.ljzn.grpc.personinfo.PersonType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *人员类型
     * </pre>
     *
     * <code>.PrisonSystem.PersonType persontype = 4;</code>
     */
    public Builder setPersontype(com.ljzn.grpc.personinfo.PersonType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      persontype_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *人员类型
     * </pre>
     *
     * <code>.PrisonSystem.PersonType persontype = 4;</code>
     */
    public Builder clearPersontype() {
      
      persontype_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object deviceSeril_ = "";
    /**
     * <code>string deviceSeril = 5;</code>
     */
    public java.lang.String getDeviceSeril() {
      java.lang.Object ref = deviceSeril_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceSeril_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string deviceSeril = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceSerilBytes() {
      java.lang.Object ref = deviceSeril_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceSeril_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string deviceSeril = 5;</code>
     */
    public Builder setDeviceSeril(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceSeril_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string deviceSeril = 5;</code>
     */
    public Builder clearDeviceSeril() {
      
      deviceSeril_ = getDefaultInstance().getDeviceSeril();
      onChanged();
      return this;
    }
    /**
     * <code>string deviceSeril = 5;</code>
     */
    public Builder setDeviceSerilBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceSeril_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PrisonSystem.PersoninfoRequest)
  }

  // @@protoc_insertion_point(class_scope:PrisonSystem.PersoninfoRequest)
  private static final com.ljzn.grpc.personinfo.PersoninfoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ljzn.grpc.personinfo.PersoninfoRequest();
  }

  public static com.ljzn.grpc.personinfo.PersoninfoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersoninfoRequest>
      PARSER = new com.google.protobuf.AbstractParser<PersoninfoRequest>() {
    public PersoninfoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PersoninfoRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PersoninfoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersoninfoRequest> getParserForType() {
    return PARSER;
  }

  public com.ljzn.grpc.personinfo.PersoninfoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

