// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.message.proto

package com.ljzn.grpc.personinfo;

/**
 * <pre>
 *人员基本信息
 * </pre>
 *
 * Protobuf type {@code PrisonSystem.PersoninfoMessage}
 */
public  final class PersoninfoMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PrisonSystem.PersoninfoMessage)
    PersoninfoMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PersoninfoMessage.newBuilder() to construct.
  private PersoninfoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersoninfoMessage() {
    cardId_ = "";
    name_ = "";
    persontype_ = 0;
    photoFeature_ = java.util.Collections.emptyList();
    photoFeatureLen_ = 0L;
    photo_ = com.google.protobuf.ByteString.EMPTY;
    version_ = 0L;
    action_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PersoninfoMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            cardId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            persontype_ = rawValue;
            break;
          }
          case 37: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              photoFeature_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000008;
            }
            photoFeature_.add(input.readFloat());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
              photoFeature_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000008;
            }
            while (input.getBytesUntilLimit() > 0) {
              photoFeature_.add(input.readFloat());
            }
            input.popLimit(limit);
            break;
          }
          case 40: {

            photoFeatureLen_ = input.readInt64();
            break;
          }
          case 50: {

            photo_ = input.readBytes();
            break;
          }
          case 56: {

            version_ = input.readInt64();
            break;
          }
          case 64: {

            action_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        photoFeature_ = java.util.Collections.unmodifiableList(photoFeature_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.internal_static_PrisonSystem_PersoninfoMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.internal_static_PrisonSystem_PersoninfoMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ljzn.grpc.personinfo.PersoninfoMessage.class, com.ljzn.grpc.personinfo.PersoninfoMessage.Builder.class);
  }

  private int bitField0_;
  public static final int CARDID_FIELD_NUMBER = 1;
  private volatile java.lang.Object cardId_;
  /**
   * <pre>
   *工作证号(编号)
   * </pre>
   *
   * <code>string cardId = 1;</code>
   */
  public java.lang.String getCardId() {
    java.lang.Object ref = cardId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *工作证号(编号)
   * </pre>
   *
   * <code>string cardId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCardIdBytes() {
    java.lang.Object ref = cardId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *姓名
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *姓名
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERSONTYPE_FIELD_NUMBER = 3;
  private int persontype_;
  /**
   * <pre>
   *人员类型
   * </pre>
   *
   * <code>.PrisonSystem.PersonType persontype = 3;</code>
   */
  public int getPersontypeValue() {
    return persontype_;
  }
  /**
   * <pre>
   *人员类型
   * </pre>
   *
   * <code>.PrisonSystem.PersonType persontype = 3;</code>
   */
  public com.ljzn.grpc.personinfo.PersonType getPersontype() {
    com.ljzn.grpc.personinfo.PersonType result = com.ljzn.grpc.personinfo.PersonType.valueOf(persontype_);
    return result == null ? com.ljzn.grpc.personinfo.PersonType.UNRECOGNIZED : result;
  }

  public static final int PHOTOFEATURE_FIELD_NUMBER = 4;
  private java.util.List<java.lang.Float> photoFeature_;
  /**
   * <pre>
   *特征(windows)
   * </pre>
   *
   * <code>repeated float photoFeature = 4;</code>
   */
  public java.util.List<java.lang.Float>
      getPhotoFeatureList() {
    return photoFeature_;
  }
  /**
   * <pre>
   *特征(windows)
   * </pre>
   *
   * <code>repeated float photoFeature = 4;</code>
   */
  public int getPhotoFeatureCount() {
    return photoFeature_.size();
  }
  /**
   * <pre>
   *特征(windows)
   * </pre>
   *
   * <code>repeated float photoFeature = 4;</code>
   */
  public float getPhotoFeature(int index) {
    return photoFeature_.get(index);
  }
  private int photoFeatureMemoizedSerializedSize = -1;

  public static final int PHOTOFEATURELEN_FIELD_NUMBER = 5;
  private long photoFeatureLen_;
  /**
   * <pre>
   *特征长度
   * </pre>
   *
   * <code>int64 photoFeatureLen = 5;</code>
   */
  public long getPhotoFeatureLen() {
    return photoFeatureLen_;
  }

  public static final int PHOTO_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString photo_;
  /**
   * <pre>
   *照片（可选)
   * </pre>
   *
   * <code>bytes photo = 6;</code>
   */
  public com.google.protobuf.ByteString getPhoto() {
    return photo_;
  }

  public static final int VERSION_FIELD_NUMBER = 7;
  private long version_;
  /**
   * <code>int64 version = 7;</code>
   */
  public long getVersion() {
    return version_;
  }

  public static final int ACTION_FIELD_NUMBER = 8;
  private int action_;
  /**
   * <pre>
   *操作 -1删除  1 增加 2 更新
   * </pre>
   *
   * <code>int32 action = 8;</code>
   */
  public int getAction() {
    return action_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getCardIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cardId_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (persontype_ != com.ljzn.grpc.personinfo.PersonType.Police.getNumber()) {
      output.writeEnum(3, persontype_);
    }
    if (getPhotoFeatureList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(photoFeatureMemoizedSerializedSize);
    }
    for (int i = 0; i < photoFeature_.size(); i++) {
      output.writeFloatNoTag(photoFeature_.get(i));
    }
    if (photoFeatureLen_ != 0L) {
      output.writeInt64(5, photoFeatureLen_);
    }
    if (!photo_.isEmpty()) {
      output.writeBytes(6, photo_);
    }
    if (version_ != 0L) {
      output.writeInt64(7, version_);
    }
    if (action_ != 0) {
      output.writeInt32(8, action_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCardIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cardId_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (persontype_ != com.ljzn.grpc.personinfo.PersonType.Police.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, persontype_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getPhotoFeatureList().size();
      size += dataSize;
      if (!getPhotoFeatureList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      photoFeatureMemoizedSerializedSize = dataSize;
    }
    if (photoFeatureLen_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, photoFeatureLen_);
    }
    if (!photo_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, photo_);
    }
    if (version_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, version_);
    }
    if (action_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, action_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ljzn.grpc.personinfo.PersoninfoMessage)) {
      return super.equals(obj);
    }
    com.ljzn.grpc.personinfo.PersoninfoMessage other = (com.ljzn.grpc.personinfo.PersoninfoMessage) obj;

    boolean result = true;
    result = result && getCardId()
        .equals(other.getCardId());
    result = result && getName()
        .equals(other.getName());
    result = result && persontype_ == other.persontype_;
    result = result && getPhotoFeatureList()
        .equals(other.getPhotoFeatureList());
    result = result && (getPhotoFeatureLen()
        == other.getPhotoFeatureLen());
    result = result && getPhoto()
        .equals(other.getPhoto());
    result = result && (getVersion()
        == other.getVersion());
    result = result && (getAction()
        == other.getAction());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CARDID_FIELD_NUMBER;
    hash = (53 * hash) + getCardId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + PERSONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + persontype_;
    if (getPhotoFeatureCount() > 0) {
      hash = (37 * hash) + PHOTOFEATURE_FIELD_NUMBER;
      hash = (53 * hash) + getPhotoFeatureList().hashCode();
    }
    hash = (37 * hash) + PHOTOFEATURELEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPhotoFeatureLen());
    hash = (37 * hash) + PHOTO_FIELD_NUMBER;
    hash = (53 * hash) + getPhoto().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVersion());
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ljzn.grpc.personinfo.PersoninfoMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.PersoninfoMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ljzn.grpc.personinfo.PersoninfoMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *人员基本信息
   * </pre>
   *
   * Protobuf type {@code PrisonSystem.PersoninfoMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PrisonSystem.PersoninfoMessage)
      com.ljzn.grpc.personinfo.PersoninfoMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.internal_static_PrisonSystem_PersoninfoMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.internal_static_PrisonSystem_PersoninfoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.personinfo.PersoninfoMessage.class, com.ljzn.grpc.personinfo.PersoninfoMessage.Builder.class);
    }

    // Construct using com.ljzn.grpc.personinfo.PersoninfoMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      cardId_ = "";

      name_ = "";

      persontype_ = 0;

      photoFeature_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      photoFeatureLen_ = 0L;

      photo_ = com.google.protobuf.ByteString.EMPTY;

      version_ = 0L;

      action_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.internal_static_PrisonSystem_PersoninfoMessage_descriptor;
    }

    public com.ljzn.grpc.personinfo.PersoninfoMessage getDefaultInstanceForType() {
      return com.ljzn.grpc.personinfo.PersoninfoMessage.getDefaultInstance();
    }

    public com.ljzn.grpc.personinfo.PersoninfoMessage build() {
      com.ljzn.grpc.personinfo.PersoninfoMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ljzn.grpc.personinfo.PersoninfoMessage buildPartial() {
      com.ljzn.grpc.personinfo.PersoninfoMessage result = new com.ljzn.grpc.personinfo.PersoninfoMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.cardId_ = cardId_;
      result.name_ = name_;
      result.persontype_ = persontype_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        photoFeature_ = java.util.Collections.unmodifiableList(photoFeature_);
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.photoFeature_ = photoFeature_;
      result.photoFeatureLen_ = photoFeatureLen_;
      result.photo_ = photo_;
      result.version_ = version_;
      result.action_ = action_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ljzn.grpc.personinfo.PersoninfoMessage) {
        return mergeFrom((com.ljzn.grpc.personinfo.PersoninfoMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ljzn.grpc.personinfo.PersoninfoMessage other) {
      if (other == com.ljzn.grpc.personinfo.PersoninfoMessage.getDefaultInstance()) return this;
      if (!other.getCardId().isEmpty()) {
        cardId_ = other.cardId_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.persontype_ != 0) {
        setPersontypeValue(other.getPersontypeValue());
      }
      if (!other.photoFeature_.isEmpty()) {
        if (photoFeature_.isEmpty()) {
          photoFeature_ = other.photoFeature_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensurePhotoFeatureIsMutable();
          photoFeature_.addAll(other.photoFeature_);
        }
        onChanged();
      }
      if (other.getPhotoFeatureLen() != 0L) {
        setPhotoFeatureLen(other.getPhotoFeatureLen());
      }
      if (other.getPhoto() != com.google.protobuf.ByteString.EMPTY) {
        setPhoto(other.getPhoto());
      }
      if (other.getVersion() != 0L) {
        setVersion(other.getVersion());
      }
      if (other.getAction() != 0) {
        setAction(other.getAction());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ljzn.grpc.personinfo.PersoninfoMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ljzn.grpc.personinfo.PersoninfoMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object cardId_ = "";
    /**
     * <pre>
     *工作证号(编号)
     * </pre>
     *
     * <code>string cardId = 1;</code>
     */
    public java.lang.String getCardId() {
      java.lang.Object ref = cardId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *工作证号(编号)
     * </pre>
     *
     * <code>string cardId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCardIdBytes() {
      java.lang.Object ref = cardId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *工作证号(编号)
     * </pre>
     *
     * <code>string cardId = 1;</code>
     */
    public Builder setCardId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *工作证号(编号)
     * </pre>
     *
     * <code>string cardId = 1;</code>
     */
    public Builder clearCardId() {
      
      cardId_ = getDefaultInstance().getCardId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *工作证号(编号)
     * </pre>
     *
     * <code>string cardId = 1;</code>
     */
    public Builder setCardIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int persontype_ = 0;
    /**
     * <pre>
     *人员类型
     * </pre>
     *
     * <code>.PrisonSystem.PersonType persontype = 3;</code>
     */
    public int getPersontypeValue() {
      return persontype_;
    }
    /**
     * <pre>
     *人员类型
     * </pre>
     *
     * <code>.PrisonSystem.PersonType persontype = 3;</code>
     */
    public Builder setPersontypeValue(int value) {
      persontype_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *人员类型
     * </pre>
     *
     * <code>.PrisonSystem.PersonType persontype = 3;</code>
     */
    public com.ljzn.grpc.personinfo.PersonType getPersontype() {
      com.ljzn.grpc.personinfo.PersonType result = com.ljzn.grpc.personinfo.PersonType.valueOf(persontype_);
      return result == null ? com.ljzn.grpc.personinfo.PersonType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *人员类型
     * </pre>
     *
     * <code>.PrisonSystem.PersonType persontype = 3;</code>
     */
    public Builder setPersontype(com.ljzn.grpc.personinfo.PersonType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      persontype_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *人员类型
     * </pre>
     *
     * <code>.PrisonSystem.PersonType persontype = 3;</code>
     */
    public Builder clearPersontype() {
      
      persontype_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Float> photoFeature_ = java.util.Collections.emptyList();
    private void ensurePhotoFeatureIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        photoFeature_ = new java.util.ArrayList<java.lang.Float>(photoFeature_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <pre>
     *特征(windows)
     * </pre>
     *
     * <code>repeated float photoFeature = 4;</code>
     */
    public java.util.List<java.lang.Float>
        getPhotoFeatureList() {
      return java.util.Collections.unmodifiableList(photoFeature_);
    }
    /**
     * <pre>
     *特征(windows)
     * </pre>
     *
     * <code>repeated float photoFeature = 4;</code>
     */
    public int getPhotoFeatureCount() {
      return photoFeature_.size();
    }
    /**
     * <pre>
     *特征(windows)
     * </pre>
     *
     * <code>repeated float photoFeature = 4;</code>
     */
    public float getPhotoFeature(int index) {
      return photoFeature_.get(index);
    }
    /**
     * <pre>
     *特征(windows)
     * </pre>
     *
     * <code>repeated float photoFeature = 4;</code>
     */
    public Builder setPhotoFeature(
        int index, float value) {
      ensurePhotoFeatureIsMutable();
      photoFeature_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *特征(windows)
     * </pre>
     *
     * <code>repeated float photoFeature = 4;</code>
     */
    public Builder addPhotoFeature(float value) {
      ensurePhotoFeatureIsMutable();
      photoFeature_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *特征(windows)
     * </pre>
     *
     * <code>repeated float photoFeature = 4;</code>
     */
    public Builder addAllPhotoFeature(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensurePhotoFeatureIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, photoFeature_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *特征(windows)
     * </pre>
     *
     * <code>repeated float photoFeature = 4;</code>
     */
    public Builder clearPhotoFeature() {
      photoFeature_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private long photoFeatureLen_ ;
    /**
     * <pre>
     *特征长度
     * </pre>
     *
     * <code>int64 photoFeatureLen = 5;</code>
     */
    public long getPhotoFeatureLen() {
      return photoFeatureLen_;
    }
    /**
     * <pre>
     *特征长度
     * </pre>
     *
     * <code>int64 photoFeatureLen = 5;</code>
     */
    public Builder setPhotoFeatureLen(long value) {
      
      photoFeatureLen_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *特征长度
     * </pre>
     *
     * <code>int64 photoFeatureLen = 5;</code>
     */
    public Builder clearPhotoFeatureLen() {
      
      photoFeatureLen_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString photo_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *照片（可选)
     * </pre>
     *
     * <code>bytes photo = 6;</code>
     */
    public com.google.protobuf.ByteString getPhoto() {
      return photo_;
    }
    /**
     * <pre>
     *照片（可选)
     * </pre>
     *
     * <code>bytes photo = 6;</code>
     */
    public Builder setPhoto(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      photo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *照片（可选)
     * </pre>
     *
     * <code>bytes photo = 6;</code>
     */
    public Builder clearPhoto() {
      
      photo_ = getDefaultInstance().getPhoto();
      onChanged();
      return this;
    }

    private long version_ ;
    /**
     * <code>int64 version = 7;</code>
     */
    public long getVersion() {
      return version_;
    }
    /**
     * <code>int64 version = 7;</code>
     */
    public Builder setVersion(long value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 version = 7;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0L;
      onChanged();
      return this;
    }

    private int action_ ;
    /**
     * <pre>
     *操作 -1删除  1 增加 2 更新
     * </pre>
     *
     * <code>int32 action = 8;</code>
     */
    public int getAction() {
      return action_;
    }
    /**
     * <pre>
     *操作 -1删除  1 增加 2 更新
     * </pre>
     *
     * <code>int32 action = 8;</code>
     */
    public Builder setAction(int value) {
      
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *操作 -1删除  1 增加 2 更新
     * </pre>
     *
     * <code>int32 action = 8;</code>
     */
    public Builder clearAction() {
      
      action_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PrisonSystem.PersoninfoMessage)
  }

  // @@protoc_insertion_point(class_scope:PrisonSystem.PersoninfoMessage)
  private static final com.ljzn.grpc.personinfo.PersoninfoMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ljzn.grpc.personinfo.PersoninfoMessage();
  }

  public static com.ljzn.grpc.personinfo.PersoninfoMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersoninfoMessage>
      PARSER = new com.google.protobuf.AbstractParser<PersoninfoMessage>() {
    public PersoninfoMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PersoninfoMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PersoninfoMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersoninfoMessage> getParserForType() {
    return PARSER;
  }

  public com.ljzn.grpc.personinfo.PersoninfoMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

