// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.service.proto

package com.ljzn.grpc.personinfo;

public final class PersoninfoService {
  private PersoninfoService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrisonSystem_PersoninfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrisonSystem_PersoninfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrisonSystem_PersoninfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrisonSystem_PersoninfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrisonSystem_UploadRecordInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrisonSystem_UploadRecordInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrisonSystem_UploadRecordInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrisonSystem_UploadRecordInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#personinfo/personinfo.service.proto\022\014P" +
      "risonSystem\032#personinfo/personinfo.messa" +
      "ge.proto\"\214\001\n\021PersoninfoRequest\022\017\n\007versio" +
      "n\030\001 \001(\003\022\021\n\tneedPhoto\030\002 \001(\010\022\020\n\010belongId\030\003" +
      " \001(\t\022,\n\npersontype\030\004 \001(\0162\030.PrisonSystem." +
      "PersonType\022\023\n\013deviceSeril\030\005 \001(\t\"h\n\022Perso" +
      "ninfoResponse\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002" +
      " \001(\t\0223\n\npersonInfo\030\003 \003(\0132\037.PrisonSystem." +
      "PersoninfoMessage\"G\n\027UploadRecordInfoReq" +
      "uest\022,\n\nrecordInfo\030\001 \003(\0132\030.PrisonSystem." +
      "RecordInfo\"9\n\030UploadRecordInfoResponse\022\014" +
      "\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t2\322\001\n\025Person" +
      "InfoAuthService\022T\n\rGetPersonInfo\022\037.Priso" +
      "nSystem.PersoninfoRequest\032 .PrisonSystem" +
      ".PersoninfoResponse\"\000\022c\n\020UploadRecordInf" +
      "o\022%.PrisonSystem.UploadRecordInfoRequest" +
      "\032&.PrisonSystem.UploadRecordInfoResponse" +
      "\"\000B)\n\030com.ljzn.grpc.personinfoP\001\242\002\nPERSO" +
      "NINFOb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_PrisonSystem_PersoninfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PrisonSystem_PersoninfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrisonSystem_PersoninfoRequest_descriptor,
        new java.lang.String[] { "Version", "NeedPhoto", "BelongId", "Persontype", "DeviceSeril", });
    internal_static_PrisonSystem_PersoninfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PrisonSystem_PersoninfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrisonSystem_PersoninfoResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "PersonInfo", });
    internal_static_PrisonSystem_UploadRecordInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PrisonSystem_UploadRecordInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrisonSystem_UploadRecordInfoRequest_descriptor,
        new java.lang.String[] { "RecordInfo", });
    internal_static_PrisonSystem_UploadRecordInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PrisonSystem_UploadRecordInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrisonSystem_UploadRecordInfoResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
    com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
