// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.message.proto

package com.ljzn.grpc.personinfo;

/**
 * Protobuf enum {@code PrisonSystem.PersonType}
 */
public enum PersonType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *警
   * </pre>
   *
   * <code>Police = 0;</code>
   */
  Police(0),
  /**
   * <pre>
   *犯
   * </pre>
   *
   * <code>Criminal = 1;</code>
   */
  Criminal(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *警
   * </pre>
   *
   * <code>Police = 0;</code>
   */
  public static final int Police_VALUE = 0;
  /**
   * <pre>
   *犯
   * </pre>
   *
   * <code>Criminal = 1;</code>
   */
  public static final int Criminal_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PersonType valueOf(int value) {
    return forNumber(value);
  }

  public static PersonType forNumber(int value) {
    switch (value) {
      case 0: return Police;
      case 1: return Criminal;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PersonType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PersonType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PersonType>() {
          public PersonType findValueByNumber(int number) {
            return PersonType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final PersonType[] VALUES = values();

  public static PersonType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PersonType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:PrisonSystem.PersonType)
}

