// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.message.proto

package com.ljzn.grpc.personinfo;

public interface PersoninfoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrisonSystem.PersoninfoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *工作证号(编号)
   * </pre>
   *
   * <code>string cardId = 1;</code>
   */
  java.lang.String getCardId();
  /**
   * <pre>
   *工作证号(编号)
   * </pre>
   *
   * <code>string cardId = 1;</code>
   */
  com.google.protobuf.ByteString
      getCardIdBytes();

  /**
   * <pre>
   *姓名
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *姓名
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *人员类型
   * </pre>
   *
   * <code>.PrisonSystem.PersonType persontype = 3;</code>
   */
  int getPersontypeValue();
  /**
   * <pre>
   *人员类型
   * </pre>
   *
   * <code>.PrisonSystem.PersonType persontype = 3;</code>
   */
  com.ljzn.grpc.personinfo.PersonType getPersontype();

  /**
   * <pre>
   *特征(windows)
   * </pre>
   *
   * <code>repeated float photoFeature = 4;</code>
   */
  java.util.List<java.lang.Float> getPhotoFeatureList();
  /**
   * <pre>
   *特征(windows)
   * </pre>
   *
   * <code>repeated float photoFeature = 4;</code>
   */
  int getPhotoFeatureCount();
  /**
   * <pre>
   *特征(windows)
   * </pre>
   *
   * <code>repeated float photoFeature = 4;</code>
   */
  float getPhotoFeature(int index);

  /**
   * <pre>
   *特征长度
   * </pre>
   *
   * <code>int64 photoFeatureLen = 5;</code>
   */
  long getPhotoFeatureLen();

  /**
   * <pre>
   *照片（可选)
   * </pre>
   *
   * <code>bytes photo = 6;</code>
   */
  com.google.protobuf.ByteString getPhoto();

  /**
   * <code>int64 version = 7;</code>
   */
  long getVersion();

  /**
   * <pre>
   *操作 -1删除  1 增加 2 更新
   * </pre>
   *
   * <code>int32 action = 8;</code>
   */
  int getAction();
}
