// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.message.proto

package com.ljzn.grpc.personinfo;

public interface RecordInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrisonSystem.RecordInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *工作证号(编号)
   * </pre>
   *
   * <code>string cardId = 1;</code>
   */
  java.lang.String getCardId();
  /**
   * <pre>
   *工作证号(编号)
   * </pre>
   *
   * <code>string cardId = 1;</code>
   */
  com.google.protobuf.ByteString
      getCardIdBytes();

  /**
   * <pre>
   *姓名
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *姓名
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 比对时间 （yyyy-MM-dd HH:mm:ss)
   * </pre>
   *
   * <code>string verifyTime = 3;</code>
   */
  java.lang.String getVerifyTime();
  /**
   * <pre>
   * 比对时间 （yyyy-MM-dd HH:mm:ss)
   * </pre>
   *
   * <code>string verifyTime = 3;</code>
   */
  com.google.protobuf.ByteString
      getVerifyTimeBytes();

  /**
   * <pre>
   *比对分值
   * </pre>
   *
   * <code>float verifyScore = 4;</code>
   */
  float getVerifyScore();

  /**
   * <pre>
   *比对照片
   * </pre>
   *
   * <code>bytes verifyPhoto = 5;</code>
   */
  com.google.protobuf.ByteString getVerifyPhoto();

  /**
   * <pre>
   * 设备号
   * </pre>
   *
   * <code>string deviceSeril = 6;</code>
   */
  java.lang.String getDeviceSeril();
  /**
   * <pre>
   * 设备号
   * </pre>
   *
   * <code>string deviceSeril = 6;</code>
   */
  com.google.protobuf.ByteString
      getDeviceSerilBytes();

  /**
   * <pre>
   *比对结果
   * </pre>
   *
   * <code>string verifyResult = 7;</code>
   */
  java.lang.String getVerifyResult();
  /**
   * <pre>
   *比对结果
   * </pre>
   *
   * <code>string verifyResult = 7;</code>
   */
  com.google.protobuf.ByteString
      getVerifyResultBytes();
}
