// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.message.proto

package com.ljzn.grpc.personinfo;

/**
 * <pre>
 *记录信息
 * </pre>
 *
 * Protobuf type {@code PrisonSystem.RecordInfo}
 */
public  final class RecordInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PrisonSystem.RecordInfo)
    RecordInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecordInfo.newBuilder() to construct.
  private RecordInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecordInfo() {
    cardId_ = "";
    name_ = "";
    verifyTime_ = "";
    verifyScore_ = 0F;
    verifyPhoto_ = com.google.protobuf.ByteString.EMPTY;
    deviceSeril_ = "";
    verifyResult_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RecordInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            cardId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            verifyTime_ = s;
            break;
          }
          case 37: {

            verifyScore_ = input.readFloat();
            break;
          }
          case 42: {

            verifyPhoto_ = input.readBytes();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceSeril_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            verifyResult_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.internal_static_PrisonSystem_RecordInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.internal_static_PrisonSystem_RecordInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ljzn.grpc.personinfo.RecordInfo.class, com.ljzn.grpc.personinfo.RecordInfo.Builder.class);
  }

  public static final int CARDID_FIELD_NUMBER = 1;
  private volatile java.lang.Object cardId_;
  /**
   * <pre>
   *工作证号(编号)
   * </pre>
   *
   * <code>string cardId = 1;</code>
   */
  public java.lang.String getCardId() {
    java.lang.Object ref = cardId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *工作证号(编号)
   * </pre>
   *
   * <code>string cardId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCardIdBytes() {
    java.lang.Object ref = cardId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *姓名
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *姓名
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFYTIME_FIELD_NUMBER = 3;
  private volatile java.lang.Object verifyTime_;
  /**
   * <pre>
   * 比对时间 （yyyy-MM-dd HH:mm:ss)
   * </pre>
   *
   * <code>string verifyTime = 3;</code>
   */
  public java.lang.String getVerifyTime() {
    java.lang.Object ref = verifyTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      verifyTime_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 比对时间 （yyyy-MM-dd HH:mm:ss)
   * </pre>
   *
   * <code>string verifyTime = 3;</code>
   */
  public com.google.protobuf.ByteString
      getVerifyTimeBytes() {
    java.lang.Object ref = verifyTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      verifyTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFYSCORE_FIELD_NUMBER = 4;
  private float verifyScore_;
  /**
   * <pre>
   *比对分值
   * </pre>
   *
   * <code>float verifyScore = 4;</code>
   */
  public float getVerifyScore() {
    return verifyScore_;
  }

  public static final int VERIFYPHOTO_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString verifyPhoto_;
  /**
   * <pre>
   *比对照片
   * </pre>
   *
   * <code>bytes verifyPhoto = 5;</code>
   */
  public com.google.protobuf.ByteString getVerifyPhoto() {
    return verifyPhoto_;
  }

  public static final int DEVICESERIL_FIELD_NUMBER = 6;
  private volatile java.lang.Object deviceSeril_;
  /**
   * <pre>
   * 设备号
   * </pre>
   *
   * <code>string deviceSeril = 6;</code>
   */
  public java.lang.String getDeviceSeril() {
    java.lang.Object ref = deviceSeril_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceSeril_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备号
   * </pre>
   *
   * <code>string deviceSeril = 6;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceSerilBytes() {
    java.lang.Object ref = deviceSeril_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceSeril_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFYRESULT_FIELD_NUMBER = 7;
  private volatile java.lang.Object verifyResult_;
  /**
   * <pre>
   *比对结果
   * </pre>
   *
   * <code>string verifyResult = 7;</code>
   */
  public java.lang.String getVerifyResult() {
    java.lang.Object ref = verifyResult_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      verifyResult_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *比对结果
   * </pre>
   *
   * <code>string verifyResult = 7;</code>
   */
  public com.google.protobuf.ByteString
      getVerifyResultBytes() {
    java.lang.Object ref = verifyResult_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      verifyResult_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCardIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cardId_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getVerifyTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, verifyTime_);
    }
    if (verifyScore_ != 0F) {
      output.writeFloat(4, verifyScore_);
    }
    if (!verifyPhoto_.isEmpty()) {
      output.writeBytes(5, verifyPhoto_);
    }
    if (!getDeviceSerilBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, deviceSeril_);
    }
    if (!getVerifyResultBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, verifyResult_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCardIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cardId_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getVerifyTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, verifyTime_);
    }
    if (verifyScore_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, verifyScore_);
    }
    if (!verifyPhoto_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, verifyPhoto_);
    }
    if (!getDeviceSerilBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, deviceSeril_);
    }
    if (!getVerifyResultBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, verifyResult_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ljzn.grpc.personinfo.RecordInfo)) {
      return super.equals(obj);
    }
    com.ljzn.grpc.personinfo.RecordInfo other = (com.ljzn.grpc.personinfo.RecordInfo) obj;

    boolean result = true;
    result = result && getCardId()
        .equals(other.getCardId());
    result = result && getName()
        .equals(other.getName());
    result = result && getVerifyTime()
        .equals(other.getVerifyTime());
    result = result && (
        java.lang.Float.floatToIntBits(getVerifyScore())
        == java.lang.Float.floatToIntBits(
            other.getVerifyScore()));
    result = result && getVerifyPhoto()
        .equals(other.getVerifyPhoto());
    result = result && getDeviceSeril()
        .equals(other.getDeviceSeril());
    result = result && getVerifyResult()
        .equals(other.getVerifyResult());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CARDID_FIELD_NUMBER;
    hash = (53 * hash) + getCardId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + VERIFYTIME_FIELD_NUMBER;
    hash = (53 * hash) + getVerifyTime().hashCode();
    hash = (37 * hash) + VERIFYSCORE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getVerifyScore());
    hash = (37 * hash) + VERIFYPHOTO_FIELD_NUMBER;
    hash = (53 * hash) + getVerifyPhoto().hashCode();
    hash = (37 * hash) + DEVICESERIL_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceSeril().hashCode();
    hash = (37 * hash) + VERIFYRESULT_FIELD_NUMBER;
    hash = (53 * hash) + getVerifyResult().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ljzn.grpc.personinfo.RecordInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.RecordInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.RecordInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.RecordInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.RecordInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.RecordInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.RecordInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.RecordInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.RecordInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.RecordInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.RecordInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.RecordInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ljzn.grpc.personinfo.RecordInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *记录信息
   * </pre>
   *
   * Protobuf type {@code PrisonSystem.RecordInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PrisonSystem.RecordInfo)
      com.ljzn.grpc.personinfo.RecordInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.internal_static_PrisonSystem_RecordInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.internal_static_PrisonSystem_RecordInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.personinfo.RecordInfo.class, com.ljzn.grpc.personinfo.RecordInfo.Builder.class);
    }

    // Construct using com.ljzn.grpc.personinfo.RecordInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      cardId_ = "";

      name_ = "";

      verifyTime_ = "";

      verifyScore_ = 0F;

      verifyPhoto_ = com.google.protobuf.ByteString.EMPTY;

      deviceSeril_ = "";

      verifyResult_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ljzn.grpc.personinfo.PersoninfoMessageOuterClass.internal_static_PrisonSystem_RecordInfo_descriptor;
    }

    public com.ljzn.grpc.personinfo.RecordInfo getDefaultInstanceForType() {
      return com.ljzn.grpc.personinfo.RecordInfo.getDefaultInstance();
    }

    public com.ljzn.grpc.personinfo.RecordInfo build() {
      com.ljzn.grpc.personinfo.RecordInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ljzn.grpc.personinfo.RecordInfo buildPartial() {
      com.ljzn.grpc.personinfo.RecordInfo result = new com.ljzn.grpc.personinfo.RecordInfo(this);
      result.cardId_ = cardId_;
      result.name_ = name_;
      result.verifyTime_ = verifyTime_;
      result.verifyScore_ = verifyScore_;
      result.verifyPhoto_ = verifyPhoto_;
      result.deviceSeril_ = deviceSeril_;
      result.verifyResult_ = verifyResult_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ljzn.grpc.personinfo.RecordInfo) {
        return mergeFrom((com.ljzn.grpc.personinfo.RecordInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ljzn.grpc.personinfo.RecordInfo other) {
      if (other == com.ljzn.grpc.personinfo.RecordInfo.getDefaultInstance()) return this;
      if (!other.getCardId().isEmpty()) {
        cardId_ = other.cardId_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getVerifyTime().isEmpty()) {
        verifyTime_ = other.verifyTime_;
        onChanged();
      }
      if (other.getVerifyScore() != 0F) {
        setVerifyScore(other.getVerifyScore());
      }
      if (other.getVerifyPhoto() != com.google.protobuf.ByteString.EMPTY) {
        setVerifyPhoto(other.getVerifyPhoto());
      }
      if (!other.getDeviceSeril().isEmpty()) {
        deviceSeril_ = other.deviceSeril_;
        onChanged();
      }
      if (!other.getVerifyResult().isEmpty()) {
        verifyResult_ = other.verifyResult_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ljzn.grpc.personinfo.RecordInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ljzn.grpc.personinfo.RecordInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object cardId_ = "";
    /**
     * <pre>
     *工作证号(编号)
     * </pre>
     *
     * <code>string cardId = 1;</code>
     */
    public java.lang.String getCardId() {
      java.lang.Object ref = cardId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *工作证号(编号)
     * </pre>
     *
     * <code>string cardId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCardIdBytes() {
      java.lang.Object ref = cardId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *工作证号(编号)
     * </pre>
     *
     * <code>string cardId = 1;</code>
     */
    public Builder setCardId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *工作证号(编号)
     * </pre>
     *
     * <code>string cardId = 1;</code>
     */
    public Builder clearCardId() {
      
      cardId_ = getDefaultInstance().getCardId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *工作证号(编号)
     * </pre>
     *
     * <code>string cardId = 1;</code>
     */
    public Builder setCardIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object verifyTime_ = "";
    /**
     * <pre>
     * 比对时间 （yyyy-MM-dd HH:mm:ss)
     * </pre>
     *
     * <code>string verifyTime = 3;</code>
     */
    public java.lang.String getVerifyTime() {
      java.lang.Object ref = verifyTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        verifyTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 比对时间 （yyyy-MM-dd HH:mm:ss)
     * </pre>
     *
     * <code>string verifyTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVerifyTimeBytes() {
      java.lang.Object ref = verifyTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verifyTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 比对时间 （yyyy-MM-dd HH:mm:ss)
     * </pre>
     *
     * <code>string verifyTime = 3;</code>
     */
    public Builder setVerifyTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      verifyTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 比对时间 （yyyy-MM-dd HH:mm:ss)
     * </pre>
     *
     * <code>string verifyTime = 3;</code>
     */
    public Builder clearVerifyTime() {
      
      verifyTime_ = getDefaultInstance().getVerifyTime();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 比对时间 （yyyy-MM-dd HH:mm:ss)
     * </pre>
     *
     * <code>string verifyTime = 3;</code>
     */
    public Builder setVerifyTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      verifyTime_ = value;
      onChanged();
      return this;
    }

    private float verifyScore_ ;
    /**
     * <pre>
     *比对分值
     * </pre>
     *
     * <code>float verifyScore = 4;</code>
     */
    public float getVerifyScore() {
      return verifyScore_;
    }
    /**
     * <pre>
     *比对分值
     * </pre>
     *
     * <code>float verifyScore = 4;</code>
     */
    public Builder setVerifyScore(float value) {
      
      verifyScore_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *比对分值
     * </pre>
     *
     * <code>float verifyScore = 4;</code>
     */
    public Builder clearVerifyScore() {
      
      verifyScore_ = 0F;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString verifyPhoto_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *比对照片
     * </pre>
     *
     * <code>bytes verifyPhoto = 5;</code>
     */
    public com.google.protobuf.ByteString getVerifyPhoto() {
      return verifyPhoto_;
    }
    /**
     * <pre>
     *比对照片
     * </pre>
     *
     * <code>bytes verifyPhoto = 5;</code>
     */
    public Builder setVerifyPhoto(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      verifyPhoto_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *比对照片
     * </pre>
     *
     * <code>bytes verifyPhoto = 5;</code>
     */
    public Builder clearVerifyPhoto() {
      
      verifyPhoto_ = getDefaultInstance().getVerifyPhoto();
      onChanged();
      return this;
    }

    private java.lang.Object deviceSeril_ = "";
    /**
     * <pre>
     * 设备号
     * </pre>
     *
     * <code>string deviceSeril = 6;</code>
     */
    public java.lang.String getDeviceSeril() {
      java.lang.Object ref = deviceSeril_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceSeril_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 设备号
     * </pre>
     *
     * <code>string deviceSeril = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceSerilBytes() {
      java.lang.Object ref = deviceSeril_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceSeril_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备号
     * </pre>
     *
     * <code>string deviceSeril = 6;</code>
     */
    public Builder setDeviceSeril(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceSeril_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备号
     * </pre>
     *
     * <code>string deviceSeril = 6;</code>
     */
    public Builder clearDeviceSeril() {
      
      deviceSeril_ = getDefaultInstance().getDeviceSeril();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备号
     * </pre>
     *
     * <code>string deviceSeril = 6;</code>
     */
    public Builder setDeviceSerilBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceSeril_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object verifyResult_ = "";
    /**
     * <pre>
     *比对结果
     * </pre>
     *
     * <code>string verifyResult = 7;</code>
     */
    public java.lang.String getVerifyResult() {
      java.lang.Object ref = verifyResult_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        verifyResult_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *比对结果
     * </pre>
     *
     * <code>string verifyResult = 7;</code>
     */
    public com.google.protobuf.ByteString
        getVerifyResultBytes() {
      java.lang.Object ref = verifyResult_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verifyResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *比对结果
     * </pre>
     *
     * <code>string verifyResult = 7;</code>
     */
    public Builder setVerifyResult(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      verifyResult_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *比对结果
     * </pre>
     *
     * <code>string verifyResult = 7;</code>
     */
    public Builder clearVerifyResult() {
      
      verifyResult_ = getDefaultInstance().getVerifyResult();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *比对结果
     * </pre>
     *
     * <code>string verifyResult = 7;</code>
     */
    public Builder setVerifyResultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      verifyResult_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PrisonSystem.RecordInfo)
  }

  // @@protoc_insertion_point(class_scope:PrisonSystem.RecordInfo)
  private static final com.ljzn.grpc.personinfo.RecordInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ljzn.grpc.personinfo.RecordInfo();
  }

  public static com.ljzn.grpc.personinfo.RecordInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecordInfo>
      PARSER = new com.google.protobuf.AbstractParser<RecordInfo>() {
    public RecordInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RecordInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RecordInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecordInfo> getParserForType() {
    return PARSER;
  }

  public com.ljzn.grpc.personinfo.RecordInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

