// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.service.proto

package com.ljzn.grpc.personinfo;

public interface UploadRecordInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrisonSystem.UploadRecordInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *新平台统一GRPC接口返回码 成功为1 ,失败为-1)
   * </pre>
   *
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
