// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.service.proto

package com.ljzn.grpc.personinfo;

public interface UploadRecordInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrisonSystem.UploadRecordInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
   */
  java.util.List<com.ljzn.grpc.personinfo.RecordInfo> 
      getRecordInfoList();
  /**
   * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
   */
  com.ljzn.grpc.personinfo.RecordInfo getRecordInfo(int index);
  /**
   * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
   */
  int getRecordInfoCount();
  /**
   * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
   */
  java.util.List<? extends com.ljzn.grpc.personinfo.RecordInfoOrBuilder> 
      getRecordInfoOrBuilderList();
  /**
   * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
   */
  com.ljzn.grpc.personinfo.RecordInfoOrBuilder getRecordInfoOrBuilder(
      int index);
}
