// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personinfo/personinfo.service.proto

package com.ljzn.grpc.personinfo;

/**
 * <pre>
 *记录上传
 * </pre>
 *
 * Protobuf type {@code PrisonSystem.UploadRecordInfoRequest}
 */
public  final class UploadRecordInfoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PrisonSystem.UploadRecordInfoRequest)
    UploadRecordInfoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UploadRecordInfoRequest.newBuilder() to construct.
  private UploadRecordInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UploadRecordInfoRequest() {
    recordInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UploadRecordInfoRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              recordInfo_ = new java.util.ArrayList<com.ljzn.grpc.personinfo.RecordInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            recordInfo_.add(
                input.readMessage(com.ljzn.grpc.personinfo.RecordInfo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        recordInfo_ = java.util.Collections.unmodifiableList(recordInfo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_UploadRecordInfoRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_UploadRecordInfoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ljzn.grpc.personinfo.UploadRecordInfoRequest.class, com.ljzn.grpc.personinfo.UploadRecordInfoRequest.Builder.class);
  }

  public static final int RECORDINFO_FIELD_NUMBER = 1;
  private java.util.List<com.ljzn.grpc.personinfo.RecordInfo> recordInfo_;
  /**
   * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
   */
  public java.util.List<com.ljzn.grpc.personinfo.RecordInfo> getRecordInfoList() {
    return recordInfo_;
  }
  /**
   * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
   */
  public java.util.List<? extends com.ljzn.grpc.personinfo.RecordInfoOrBuilder> 
      getRecordInfoOrBuilderList() {
    return recordInfo_;
  }
  /**
   * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
   */
  public int getRecordInfoCount() {
    return recordInfo_.size();
  }
  /**
   * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
   */
  public com.ljzn.grpc.personinfo.RecordInfo getRecordInfo(int index) {
    return recordInfo_.get(index);
  }
  /**
   * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
   */
  public com.ljzn.grpc.personinfo.RecordInfoOrBuilder getRecordInfoOrBuilder(
      int index) {
    return recordInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < recordInfo_.size(); i++) {
      output.writeMessage(1, recordInfo_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < recordInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, recordInfo_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ljzn.grpc.personinfo.UploadRecordInfoRequest)) {
      return super.equals(obj);
    }
    com.ljzn.grpc.personinfo.UploadRecordInfoRequest other = (com.ljzn.grpc.personinfo.UploadRecordInfoRequest) obj;

    boolean result = true;
    result = result && getRecordInfoList()
        .equals(other.getRecordInfoList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRecordInfoCount() > 0) {
      hash = (37 * hash) + RECORDINFO_FIELD_NUMBER;
      hash = (53 * hash) + getRecordInfoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ljzn.grpc.personinfo.UploadRecordInfoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *记录上传
   * </pre>
   *
   * Protobuf type {@code PrisonSystem.UploadRecordInfoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PrisonSystem.UploadRecordInfoRequest)
      com.ljzn.grpc.personinfo.UploadRecordInfoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_UploadRecordInfoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_UploadRecordInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljzn.grpc.personinfo.UploadRecordInfoRequest.class, com.ljzn.grpc.personinfo.UploadRecordInfoRequest.Builder.class);
    }

    // Construct using com.ljzn.grpc.personinfo.UploadRecordInfoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRecordInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (recordInfoBuilder_ == null) {
        recordInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        recordInfoBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ljzn.grpc.personinfo.PersoninfoService.internal_static_PrisonSystem_UploadRecordInfoRequest_descriptor;
    }

    public com.ljzn.grpc.personinfo.UploadRecordInfoRequest getDefaultInstanceForType() {
      return com.ljzn.grpc.personinfo.UploadRecordInfoRequest.getDefaultInstance();
    }

    public com.ljzn.grpc.personinfo.UploadRecordInfoRequest build() {
      com.ljzn.grpc.personinfo.UploadRecordInfoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ljzn.grpc.personinfo.UploadRecordInfoRequest buildPartial() {
      com.ljzn.grpc.personinfo.UploadRecordInfoRequest result = new com.ljzn.grpc.personinfo.UploadRecordInfoRequest(this);
      int from_bitField0_ = bitField0_;
      if (recordInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          recordInfo_ = java.util.Collections.unmodifiableList(recordInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.recordInfo_ = recordInfo_;
      } else {
        result.recordInfo_ = recordInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ljzn.grpc.personinfo.UploadRecordInfoRequest) {
        return mergeFrom((com.ljzn.grpc.personinfo.UploadRecordInfoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ljzn.grpc.personinfo.UploadRecordInfoRequest other) {
      if (other == com.ljzn.grpc.personinfo.UploadRecordInfoRequest.getDefaultInstance()) return this;
      if (recordInfoBuilder_ == null) {
        if (!other.recordInfo_.isEmpty()) {
          if (recordInfo_.isEmpty()) {
            recordInfo_ = other.recordInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecordInfoIsMutable();
            recordInfo_.addAll(other.recordInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.recordInfo_.isEmpty()) {
          if (recordInfoBuilder_.isEmpty()) {
            recordInfoBuilder_.dispose();
            recordInfoBuilder_ = null;
            recordInfo_ = other.recordInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            recordInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecordInfoFieldBuilder() : null;
          } else {
            recordInfoBuilder_.addAllMessages(other.recordInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ljzn.grpc.personinfo.UploadRecordInfoRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ljzn.grpc.personinfo.UploadRecordInfoRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ljzn.grpc.personinfo.RecordInfo> recordInfo_ =
      java.util.Collections.emptyList();
    private void ensureRecordInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        recordInfo_ = new java.util.ArrayList<com.ljzn.grpc.personinfo.RecordInfo>(recordInfo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ljzn.grpc.personinfo.RecordInfo, com.ljzn.grpc.personinfo.RecordInfo.Builder, com.ljzn.grpc.personinfo.RecordInfoOrBuilder> recordInfoBuilder_;

    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public java.util.List<com.ljzn.grpc.personinfo.RecordInfo> getRecordInfoList() {
      if (recordInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(recordInfo_);
      } else {
        return recordInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public int getRecordInfoCount() {
      if (recordInfoBuilder_ == null) {
        return recordInfo_.size();
      } else {
        return recordInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public com.ljzn.grpc.personinfo.RecordInfo getRecordInfo(int index) {
      if (recordInfoBuilder_ == null) {
        return recordInfo_.get(index);
      } else {
        return recordInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public Builder setRecordInfo(
        int index, com.ljzn.grpc.personinfo.RecordInfo value) {
      if (recordInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordInfoIsMutable();
        recordInfo_.set(index, value);
        onChanged();
      } else {
        recordInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public Builder setRecordInfo(
        int index, com.ljzn.grpc.personinfo.RecordInfo.Builder builderForValue) {
      if (recordInfoBuilder_ == null) {
        ensureRecordInfoIsMutable();
        recordInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        recordInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public Builder addRecordInfo(com.ljzn.grpc.personinfo.RecordInfo value) {
      if (recordInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordInfoIsMutable();
        recordInfo_.add(value);
        onChanged();
      } else {
        recordInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public Builder addRecordInfo(
        int index, com.ljzn.grpc.personinfo.RecordInfo value) {
      if (recordInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordInfoIsMutable();
        recordInfo_.add(index, value);
        onChanged();
      } else {
        recordInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public Builder addRecordInfo(
        com.ljzn.grpc.personinfo.RecordInfo.Builder builderForValue) {
      if (recordInfoBuilder_ == null) {
        ensureRecordInfoIsMutable();
        recordInfo_.add(builderForValue.build());
        onChanged();
      } else {
        recordInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public Builder addRecordInfo(
        int index, com.ljzn.grpc.personinfo.RecordInfo.Builder builderForValue) {
      if (recordInfoBuilder_ == null) {
        ensureRecordInfoIsMutable();
        recordInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        recordInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public Builder addAllRecordInfo(
        java.lang.Iterable<? extends com.ljzn.grpc.personinfo.RecordInfo> values) {
      if (recordInfoBuilder_ == null) {
        ensureRecordInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recordInfo_);
        onChanged();
      } else {
        recordInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public Builder clearRecordInfo() {
      if (recordInfoBuilder_ == null) {
        recordInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        recordInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public Builder removeRecordInfo(int index) {
      if (recordInfoBuilder_ == null) {
        ensureRecordInfoIsMutable();
        recordInfo_.remove(index);
        onChanged();
      } else {
        recordInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public com.ljzn.grpc.personinfo.RecordInfo.Builder getRecordInfoBuilder(
        int index) {
      return getRecordInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public com.ljzn.grpc.personinfo.RecordInfoOrBuilder getRecordInfoOrBuilder(
        int index) {
      if (recordInfoBuilder_ == null) {
        return recordInfo_.get(index);  } else {
        return recordInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public java.util.List<? extends com.ljzn.grpc.personinfo.RecordInfoOrBuilder> 
         getRecordInfoOrBuilderList() {
      if (recordInfoBuilder_ != null) {
        return recordInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(recordInfo_);
      }
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public com.ljzn.grpc.personinfo.RecordInfo.Builder addRecordInfoBuilder() {
      return getRecordInfoFieldBuilder().addBuilder(
          com.ljzn.grpc.personinfo.RecordInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public com.ljzn.grpc.personinfo.RecordInfo.Builder addRecordInfoBuilder(
        int index) {
      return getRecordInfoFieldBuilder().addBuilder(
          index, com.ljzn.grpc.personinfo.RecordInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .PrisonSystem.RecordInfo recordInfo = 1;</code>
     */
    public java.util.List<com.ljzn.grpc.personinfo.RecordInfo.Builder> 
         getRecordInfoBuilderList() {
      return getRecordInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ljzn.grpc.personinfo.RecordInfo, com.ljzn.grpc.personinfo.RecordInfo.Builder, com.ljzn.grpc.personinfo.RecordInfoOrBuilder> 
        getRecordInfoFieldBuilder() {
      if (recordInfoBuilder_ == null) {
        recordInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ljzn.grpc.personinfo.RecordInfo, com.ljzn.grpc.personinfo.RecordInfo.Builder, com.ljzn.grpc.personinfo.RecordInfoOrBuilder>(
                recordInfo_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        recordInfo_ = null;
      }
      return recordInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PrisonSystem.UploadRecordInfoRequest)
  }

  // @@protoc_insertion_point(class_scope:PrisonSystem.UploadRecordInfoRequest)
  private static final com.ljzn.grpc.personinfo.UploadRecordInfoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ljzn.grpc.personinfo.UploadRecordInfoRequest();
  }

  public static com.ljzn.grpc.personinfo.UploadRecordInfoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UploadRecordInfoRequest>
      PARSER = new com.google.protobuf.AbstractParser<UploadRecordInfoRequest>() {
    public UploadRecordInfoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UploadRecordInfoRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UploadRecordInfoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UploadRecordInfoRequest> getParserForType() {
    return PARSER;
  }

  public com.ljzn.grpc.personinfo.UploadRecordInfoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

